"""Layer 2 -- reactions: templates (graph rewrites) and concrete reactions."""

from chemsim.reactions.library import (
    aerobic_oxidation,
    alcohol_chemistry,
    alkene_dehydration,
    esterification,
    ether_condensation,
    lead_chamber,
    nitric_oxide_reoxidation,
    peroxide_over_oxidation,
    sulfur_combustion,
    sulfur_dioxide_oxidation,
)
from chemsim.reactions.electrochemistry import (
    alkene_hydrodimerisation,
    electrochemistry,
    halide_electrolysis,
    kolbe_electrolysis,
    water_electrolysis,
)
from chemsim.reactions.reaction import ConcreteReaction
from chemsim.reactions.synthesis import (
    addition_chemistry,
    alkene_hydration,
    alkene_hydrogenation,
    alkyne_hydration,
    ammonia_synthesis,
    aromatic_chemistry,
    aromatic_nitration,
    bleach_chemistry,
    cannizzaro,
    condensation_chemistry,
    ester_chemistry,
    ester_hydrolysis,
    friedel_crafts_hydroxyalkylation,
    glycoside_hydrolysis,
    halogen_disproportionation,
    hydrogenation_chemistry,
    knoevenagel_doebner,
    kolbe_schmitt,
    methanol_from_carbon_dioxide,
    methanol_from_carbon_monoxide,
    n_acylation,
    nitro_hydrogenation,
    perkin_condensation,
    saponification,
    sugar_chemistry,
    synthesis_gas_chemistry,
    transesterification,
    williamson_ether_synthesis,
)
from chemsim.reactions.template import ReactionTemplate
from chemsim.reactions.thermo import (
    DetailedBalance,
    decomposition_potential,
    delta_n,
    detailed_balance,
    equilibrium_constant,
    equilibrium_constant_c,
    gibbs_at,
    reaction_deltas,
    reaction_entropy,
)

__all__ = [
    "ReactionTemplate",
    "ConcreteReaction",
    "aerobic_oxidation",
    "alcohol_chemistry",
    "alkene_dehydration",
    "esterification",
    "ether_condensation",
    "lead_chamber",
    "nitric_oxide_reoxidation",
    "peroxide_over_oxidation",
    "sulfur_combustion",
    "sulfur_dioxide_oxidation",
    # M5 -- the named-route templates, see reactions/synthesis.py
    "glycoside_hydrolysis",
    "aromatic_nitration",
    "williamson_ether_synthesis",
    "friedel_crafts_hydroxyalkylation",
    "kolbe_schmitt",
    "saponification",
    "ester_hydrolysis",
    "transesterification",
    "n_acylation",
    "cannizzaro",
    "perkin_condensation",
    "knoevenagel_doebner",
    "alkene_hydration",
    "alkyne_hydration",
    "alkene_hydrogenation",
    "nitro_hydrogenation",
    "halogen_disproportionation",
    "ammonia_synthesis",
    "methanol_from_carbon_monoxide",
    "methanol_from_carbon_dioxide",
    "sugar_chemistry",
    "ester_chemistry",
    "aromatic_chemistry",
    "condensation_chemistry",
    "addition_chemistry",
    "hydrogenation_chemistry",
    "synthesis_gas_chemistry",
    "bleach_chemistry",
    # M8 -- the electrode templates, see reactions/electrochemistry.py
    "water_electrolysis",
    "halide_electrolysis",
    "kolbe_electrolysis",
    "alkene_hydrodimerisation",
    "electrochemistry",
    "decomposition_potential",
    "reaction_deltas",
    "reaction_entropy",
    "delta_n",
    "gibbs_at",
    "equilibrium_constant",
    "equilibrium_constant_c",
    "detailed_balance",
    "DetailedBalance",
]
