"""Layer 2 -- the reaction templates, as data. GENERATED, do not edit.

    python tools/build_templates.py

Source: ``data/templates/templates.psv``. Adding a template is adding a row to
that file and running the line above; the row carries every field
``ReactionTemplate`` has, plus the tier, the catalog classes it covers, the
barrier's provenance and a note.

A ``tier="literal"`` row is extracted from ONE catalog step with kinetics from
a class policy table, and it may not enter the default library implicitly. S11
established that selectivity is a rate ratio between templates racing in the
same flask, so a hundred rows carrying policy-table kinetics would make every
multi-template flask's selectivity noise. ``load_templates()`` defaults to the
family tier and says which tier it loaded.
"""

from __future__ import annotations

from dataclasses import dataclass

from chemsim.reactions.template import ReactionTemplate

# Every field of ``ReactionTemplate`` that is data. Generated from the dataclass
# itself, so a field added there breaks the build until the table gains a column
# -- which is the assertion P4 wanted: about the SET of fields, not about
# whichever field somebody remembered.
TEMPLATE_FIELDS = (

    'name',
    'smarts',
    'A',
    'Ea',
    'reversible',
    'phase',
    'alpha',
    'orders',
    'solid_catalyst',
    'electrons',
    'hammett_rho',
    'hammett_slot',
    'hammett_saturation',
)


@dataclass(frozen=True)
class TemplateRecord:
    """One row of ``templates.psv``, as data. ``build()`` makes the template."""

    name: str
    tier: str
    catalog_classes: tuple[str, ...]
    source: str
    notes: str
    smarts: str
    A: float
    Ea: float
    reversible: bool
    phase: str
    alpha: float
    orders: tuple[float, ...] | None
    solid_catalyst: str | None
    electrons: int
    hammett_rho: float
    hammett_slot: int
    hammett_saturation: float

    def build(self) -> ReactionTemplate:
        return ReactionTemplate(**{f: getattr(self, f) for f in TEMPLATE_FIELDS})


TEMPLATES: dict[str, TemplateRecord] = {
    'fischer_esterification': TemplateRecord(
        name='fischer_esterification',
        tier='family',
        catalog_classes=('esterification',),
        source='Ea band 50-60 kJ/mol, acid-catalysed/autocatalysed Fischer esterification',
        notes='the hydrolysis is the derived reverse; the catalysed form is library.esterification(catalyst=...)',
        smarts='[CX3:1](=[O:2])[OX2H1:3].[OX2H1:4][CX4:5]>>[CX3:1](=[O:2])[O:4][CX4:5].[OH2:3]',
        A=50000000.0, Ea=55000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'ether_condensation': TemplateRecord(
        name='ether_condensation',
        tier='family',
        catalog_classes=('ether-condensation',),
        source='Ea band 100-130 kJ/mol, bimolecular ether route',
        notes='must stay BELOW alkene_dehydration: ethanol gives ether at 140 C and ethylene at 180 C',
        smarts='[CX4:1][OX2H1:2].[CX4:3][OX2H1:4]>>[C:1][O:2][C:3].[OH2:4]',
        A=100000000000.0, Ea=125000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'alkene_dehydration': TemplateRecord(
        name='alkene_dehydration',
        tier='family',
        catalog_classes=('dehydration',),
        source='Ea band 145-170 kJ/mol, unimolecular E1',
        notes='irreversible: it eliminates into a large excess of water',
        smarts='[CX4;!H0:1][CX4:2][OX2H1:3]>>[C:1]=[C:2].[OH2:3]',
        A=10000000000000.0, Ea=160000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'aerobic_oxidation': TemplateRecord(
        name='aerobic_oxidation',
        tier='family',
        catalog_classes=('alcohol-oxidation',),
        source='Ea ~65 kJ/mol, uncatalysed autoxidation',
        notes='written to H2O2 rather than half an O2; the peroxide then over-oxidises',
        smarts='[CX4;!H0:1][OX2H1:2].[OX1:3]=[OX1:4]>>[C:1]=[O:2].[OX2H1:3][OX2H1:4]',
        A=1000000000.0, Ea=65000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'peroxide_over_oxidation': TemplateRecord(
        name='peroxide_over_oxidation',
        tier='family',
        catalog_classes=('aldehyde-oxidation',),
        source='Ea ~50 kJ/mol, peroxide oxidation of an aldehyde',
        notes='aldehyde only: a ketone has no carbonyl H, so isopropanol stops at acetone',
        smarts='[CX3H1:1]=[OX1:2].[OX2H1:3][OX2H1:4]>>[CX3:1](=[O:2])[OX2H1:3].[OH2:4]',
        A=100000000.0, Ea=50000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'sulfur_dioxide_oxidation_by_nitrogen_dioxide': TemplateRecord(
        name='sulfur_dioxide_oxidation_by_nitrogen_dioxide',
        tier='family',
        catalog_classes=('redox-oxygen-transfer',),
        source='Ea band 30-50 kJ/mol, SO2 oxidation by NO2',
        notes='an apparent barrier standing in for a reaction that really runs in a droplet',
        smarts='[O:1]=[S:2]=[O:3].[N+:4](=[O:5])[O-:6].[OX2H2:7]>>[O:1]=[S:2](=[O:3])([O+0;H1:6])[O:7].[N+0;H0:4]=[O:5]',
        A=1000000000.0, Ea=40000.0,
        reversible=True, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'nitric_oxide_reoxidation': TemplateRecord(
        name='nitric_oxide_reoxidation',
        tier='family',
        catalog_classes=('gas-phase-oxidation',),
        source='Ea = -R*530 = -4.4 kJ/mol, measured; the rate RISES as it cools',
        notes='elementary and genuinely termolecular; the negative barrier is the datum',
        smarts='[N;H0:1]=[O:2].[N;H0:3]=[O:4].[OX1:5]=[OX1:6]>>[N+1;H0:1](=[O:2])[O-:5].[N+1;H0:3](=[O:4])[O-:6]',
        A=43500000000.0, Ea=-4400.0,
        reversible=True, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'sulfur_combustion': TemplateRecord(
        name='sulfur_combustion',
        tier='family',
        catalog_classes=('sulfur-combustion',),
        source='A pinned at the order of the gas-kinetic collision limit (~1e11); Ea 100 kJ/mol is then the only freedom, set so the burn is complete above ignition and negligible cold',
        notes='declared orders: first in S8, first in O2, because S8 + 8 O2 is not elementary. The 500 K threshold is SOFT and is stated, not tuned',
        smarts='[S:1]1[S:2][S:3][S:4][S:5][S:6][S:7][S:8]1.[OX1:9]=[OX1:10].[OX1:11]=[OX1:12].[OX1:13]=[OX1:14].[OX1:15]=[OX1:16].[OX1:17]=[OX1:18].[OX1:19]=[OX1:20].[OX1:21]=[OX1:22].[OX1:23]=[OX1:24]>>[O:9]=[S:1]=[O:10].[O:11]=[S:2]=[O:12].[O:13]=[S:3]=[O:14].[O:15]=[S:4]=[O:16].[O:17]=[S:5]=[O:18].[O:19]=[S:6]=[O:20].[O:21]=[S:7]=[O:22].[O:23]=[S:8]=[O:24]',
        A=10000000000.0, Ea=100000.0,
        reversible=False, phase='gas',
        alpha=0.0, orders=(1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'sulfur_trioxide_hydration': TemplateRecord(
        name='sulfur_trioxide_hydration',
        tier='family',
        catalog_classes=('sulfur-trioxide-hydration',),
        source='A at the order of the collision limit; Ea 23.6 kJ/mol puts k(298) at 7.3e5 L/(mol s), the ORDER of the reported effective constant (recalled, not sourced in this repo)',
        notes='measured in the receiver: the answer does not depend on either number',
        smarts='[OX1:1]=[SX3:2](=[OX1:3])=[OX1:4].[OX2H2:5]>>[O:1]=[S:2](=[O:3])([O;H1:4])[O;H1:5]',
        A=10000000000.0, Ea=23600.0,
        reversible=True, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'glycoside_hydrolysis': TemplateRecord(
        name='glycoside_hydrolysis',
        tier='family',
        catalog_classes=('glycoside-hydrolysis',),
        source='Ea band 100-115 kJ/mol, acid-catalysed inversion of sucrose',
        notes='A is 1e11 rather than the ~1e15 the measured rate implies, because the acid pre-equilibrium is folded into the barrier',
        smarts='[CX4;R:1]([OX2;R:2])[OX2;!R:3][#6:4].[OX2H2:5]>>[C:1]([O:2])[OX2H1:5].[OX2H1:3][#6:4]',
        A=100000000000.0, Ea=107000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'aromatic_nitration': TemplateRecord(
        name='aromatic_nitration',
        tier='family',
        catalog_classes=('electrophilic-aromatic-nitration',),
        source='Ea band 50-70 kJ/mol, nitration in mixed acid; rho -6.5 on the sigma-PLUS scale, Brown-Okamoto band -6.0 to -7.0',
        notes='hammett_rho is what makes nitration a PROCESS: a nitrated ring is deactivated, so the stages separate',
        smarts='[cH:1].[OX2H1:2][N+:3](=[O:4])[O-:5]>>[c:1][N+:3](=[O:4])[O-:5].[OX2H2:2]',
        A=10000000000.0, Ea=60000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=-6.5, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'williamson_ether_synthesis': TemplateRecord(
        name='williamson_ether_synthesis',
        tier='family',
        catalog_classes=('williamson-ether-synthesis',),
        source='Ea band 80-95 kJ/mol, SN2 of an alkoxide or phenoxide on an alkyl halide',
        notes='irreversible: the halide leaves as an anion nothing here attacks',
        smarts='[#6:4][O-;X1:1].[CX4:2][F,Cl,Br,I:3]>>[#6:4][O+0:1][C:2].[F,Cl,Br,I;-:3]',
        A=1000000000.0, Ea=85000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'friedel_crafts_hydroxyalkylation': TemplateRecord(
        name='friedel_crafts_hydroxyalkylation',
        tier='family',
        catalog_classes=('friedel-crafts-hydroxyalkylation',),
        source='Ea band 60-75 kJ/mol, bisphenol-A literature (phenol + acetone)',
        notes='',
        smarts='[cH:1].[cH:2].[CX3:3]=[OX1:4]>>[c:1][C:3][c:2].[OX2H2:4]',
        A=100000000.0, Ea=65000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'kolbe_schmitt_carboxylation': TemplateRecord(
        name='kolbe_schmitt_carboxylation',
        tier='family',
        catalog_classes=('kolbe-schmitt-carboxylation',),
        source='Ea band 85-95 kJ/mol, Kolbe-Schmitt carboxylation of sodium phenoxide',
        notes='',
        smarts='[O-:1][c:2][cH:3].[CX2:4](=[OX1:5])=[OX1:6]>>[OX2H1;+0:1][c:2][c:3][C:4](=[O:5])[O-:6]',
        A=100000000.0, Ea=90000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'saponification': TemplateRecord(
        name='saponification',
        tier='family',
        catalog_classes=('ester-hydrolysis', 'saponification'),
        source='Ea band 45-48 kJ/mol, ethyl acetate + hydroxide, one of the best-measured rate constants in chemistry',
        notes='irreversible: it ends on a carboxylate, and an alcohol does not attack one',
        smarts='[CX3:1](=[O:2])[OX2:3][#6:4].[OH-:5]>>[CX3:1](=[O:2])[O-:5].[OX2H1:3][#6:4]',
        A=100000000.0, Ea=46000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'ester_hydrolysis': TemplateRecord(
        name='ester_hydrolysis',
        tier='family',
        catalog_classes=('ester-hydrolysis',),
        source='Ea band 65-80 kJ/mol, aspirin hydrolysis',
        notes='declared in the hydrolysis direction because discovery runs templates FORWARD only',
        smarts='[CX3:1](=[O:2])[OX2:3][#6;!$([CX3]=[OX1]):4].[OX2H2:5]>>[CX3:1](=[O:2])[OX2H1:5].[OX2H1:3][#6:4]',
        A=100000000.0, Ea=70000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'transesterification': TemplateRecord(
        name='transesterification',
        tier='family',
        catalog_classes=('transesterification',),
        source='Ea band 50-70 kJ/mol, base-catalysed methanolysis of a triglyceride',
        notes='',
        smarts='[CX3:1](=[O:2])[OX2:3][CX4:4].[OX2H1:5][CX4:6]>>[CX3:1](=[O:2])[O:5][C:6].[OX2H1:3][C:4]',
        A=10000000.0, Ea=55000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'n_acylation': TemplateRecord(
        name='n_acylation',
        tier='family',
        catalog_classes=('n-acylation',),
        source='Ea band 40-55 kJ/mol, aminolysis of acetic anhydride',
        notes='',
        smarts='[NX3;H1,H2;!$(N[#6]=[O,S,N]):6].[CX3:1](=[O:2])[OX2:3][CX3:4]=[O:5]>>[N:6][C:1]=[O:2].[OX2H1:3][C:4]=[O:5]',
        A=100000000.0, Ea=45000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'cannizzaro_disproportionation': TemplateRecord(
        name='cannizzaro_disproportionation',
        tier='family',
        catalog_classes=('cannizzaro-disproportionation',),
        source='Ea band 50-60 kJ/mol, benzaldehyde in concentrated hydroxide',
        notes='',
        smarts='[c:3][CX3H1:1]=[OX1:2].[c:6][CX3H1:4]=[OX1:5].[OH-:7]>>[c:3][CH2:1][OX2H1:2].[c:6][C:4](=[O:5])[O-:7]',
        A=10000000.0, Ea=55000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'perkin_condensation': TemplateRecord(
        name='perkin_condensation',
        tier='family',
        catalog_classes=('perkin-condensation',),
        source='Ea band 90-105 kJ/mol; the Perkin reaction needs 450 K for 8 hours, which is what a barrier near 100 kJ/mol looks like',
        notes='',
        smarts='[c:1][CX3H1:2]=[OX1:3].[CH3:4][CX3:5](=[O:6])[OX2:7][CX3:8]=[O:9]>>[c:1][CH:2]=[CH:4][C:5](=[O:6])[OX2H1:7].[OX2H1:3][C:8]=[O:9]',
        A=1000000000.0, Ea=95000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'knoevenagel_doebner_condensation': TemplateRecord(
        name='knoevenagel_doebner_condensation',
        tier='family',
        catalog_classes=('knoevenagel-doebner-condensation',),
        source='Ea band 60-80 kJ/mol, amine-catalysed Doebner condensation',
        notes='',
        smarts='[c:1][CX3H1:2]=[OX1:3].[CX4H2:4]([CX3:5](=[O:6])[OX2H1:7])[CX3:8](=[O:9])[OX2H1:10]>>[c:1][CH:2]=[CH:4][C:5](=[O:6])[O:7].[C:8](=[O:9])=[O:10].[OX2H2:3]',
        A=100000000.0, Ea=70000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'alkene_hydration': TemplateRecord(
        name='alkene_hydration',
        tier='family',
        catalog_classes=('alkene-hydration',),
        source='Ea band 75-90 kJ/mol, direct hydration of ethylene over phosphoric acid',
        notes='',
        smarts='[CX3:1]=[CX3:2].[OX2H2:3]>>[C:1][C:2][OX2H1:3]',
        A=10000000000.0, Ea=80000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'alkyne_hydration': TemplateRecord(
        name='alkyne_hydration',
        tier='family',
        catalog_classes=('alkyne-hydration',),
        source='Ea band 65-80 kJ/mol, mercury(II)-catalysed',
        notes='',
        smarts='[CX2:1]#[CX2:2].[OX2H2:3]>>[C:1](=[O:3])[C:2]',
        A=1000000000.0, Ea=70000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'alkene_hydrogenation': TemplateRecord(
        name='alkene_hydrogenation',
        tier='family',
        catalog_classes=('alkene-hydrogenation',),
        source='Ea band 40-60 kJ/mol, heterogeneous alkene hydrogenation over nickel or palladium',
        notes='A is the declared 1e7 divided by SOLID_CATALYST_REFERENCE = 0.1, so the catalysed and uncatalysed forms agree at that charge',
        smarts='[CX3:1]=[CX3:2].[H:3][H:4]>>[C:1]([H:3])[C:2][H:4]',
        A=100000000.0, Ea=50000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst='nickel', electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'nitro_hydrogenation': TemplateRecord(
        name='nitro_hydrogenation',
        tier='family',
        catalog_classes=('nitro-hydrogenation',),
        source='Ea band 40-60 kJ/mol, nitrobenzene hydrogenation over nickel or copper',
        notes='A rescaled by SOLID_CATALYST_REFERENCE as above',
        smarts='[c:1][N+:2](=[O:3])[O-:4].[H:5][H:6].[H:7][H:8].[H:9][H:10]>>[c:1][N+0:2]([H:5])[H:6].[O+0:3]([H:7])[H:8].[O+0:4]([H:9])[H:10]',
        A=1000000.0, Ea=50000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst='nickel', electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'halogen_disproportionation': TemplateRecord(
        name='halogen_disproportionation',
        tier='family',
        catalog_classes=('disproportionation',),
        source='Ea ~35 kJ/mol; chlorine disproportionation in alkali is fast at room temperature',
        notes='',
        smarts='[Cl,Br,I;X1:1][Cl,Br,I;X1:2].[O;H1;X1;-:3].[O;H1;X1;-:4]>>[Cl,Br,I;-:1].[Cl,Br,I;+0:2][O-;H0:3].[O;H2;+0:4]',
        A=1000000000.0, Ea=35000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'ammonia_synthesis': TemplateRecord(
        name='ammonia_synthesis',
        tier='family',
        catalog_classes=('catalytic-gas-synthesis',),
        source='Ea band 100-170 kJ/mol, apparent barrier over promoted iron',
        notes='a GAS-phase reaction with a solid catalyst, not a solid-phase one: the phase label carries a standard state worth 2.6e10 in K',
        smarts='[N:1]#[N:2].[H:3][H:4].[H:5][H:6].[H:7][H:8]>>[N:1]([H:3])([H:5])[H:7].[N:2]([H:4])([H:6])[H:8]',
        A=10000000.0, Ea=100000.0,
        reversible=True, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst='iron', electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'methanol_from_carbon_monoxide': TemplateRecord(
        name='methanol_from_carbon_monoxide',
        tier='family',
        catalog_classes=('catalytic-gas-synthesis',),
        source='Ea band 60-85 kJ/mol, Cu/ZnO methanol synthesis',
        notes='',
        smarts='[C-:1]#[O+:2].[H:3][H:4].[H:5][H:6]>>[C+0:1]([H:3])([H:4])([H:5])[O+0:2][H:6]',
        A=10000000.0, Ea=70000.0,
        reversible=True, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst='copper', electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'methanol_from_carbon_dioxide': TemplateRecord(
        name='methanol_from_carbon_dioxide',
        tier='family',
        catalog_classes=('catalytic-gas-synthesis',),
        source='Ea 80 kJ/mol, the same catalyst on CO2, consistently the slower route',
        notes='the ordering against the CO route is the load-bearing part',
        smarts='[O:1]=[C:2]=[O:3].[H:4][H:5].[H:6][H:7].[H:8][H:9]>>[C:2]([H:4])([H:5])([H:6])[O:1][H:7].[O:3]([H:8])[H:9]',
        A=1000000.0, Ea=80000.0,
        reversible=True, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst='copper', electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'water_gas_shift': TemplateRecord(
        name='water_gas_shift',
        tier='family',
        catalog_classes=('water-gas-shift',),
        source='Ea band 95-130 kJ/mol, Fe/Cr high-temperature shift',
        notes='',
        smarts='[C-:1]#[O+:2].[OX2H2:3]>>[O+0:2]=[C+0:1]=[O:3].[H][H]',
        A=1000000000.0, Ea=110000.0,
        reversible=True, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst='hematite', electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'steam_reforming': TemplateRecord(
        name='steam_reforming',
        tier='family',
        catalog_classes=('steam-reforming',),
        source='Ea 240 kJ/mol, Xu and Froment E1 over Ni',
        notes='',
        smarts='[C;H4:1].[O;H2:2]>>[C-:1]#[O+:2].[H][H].[H][H].[H][H]',
        A=1000000000000.0, Ea=240000.0,
        reversible=True, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst='nickel', electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'deacon_oxidation': TemplateRecord(
        name='deacon_oxidation',
        tier='family',
        catalog_classes=('catalytic-hydrogen-chloride-oxidation',),
        source='Ea band 85-120 kJ/mol, Cu-catalysed HCl oxidation',
        notes='',
        smarts='[Cl;H1:1].[Cl;H1:2].[Cl;H1:3].[Cl;H1:4].[OX1:5]=[OX1:6]>>[Cl;H0:1][Cl;H0:2].[Cl;H0:3][Cl;H0:4].[O;H2:5].[O;H2:6]',
        A=100000000000000.0, Ea=100000.0,
        reversible=True, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst='tenorite', electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'hydrogen_sulfide_combustion': TemplateRecord(
        name='hydrogen_sulfide_combustion',
        tier='family',
        catalog_classes=('hydrogen-sulfide-combustion',),
        source='Ea 100 kJ/mol, on the same footing as the sulfur burner',
        notes='declared orders: first in H2S, first in O2',
        smarts='[S;H2:1].[S;H2:2].[OX1:3]=[OX1:4].[OX1:5]=[OX1:6].[OX1:7]=[OX1:8]>>[O:3]=[S;H0:1]=[O:4].[O:5]=[S;H0:2]=[O:6].[O;H2:7].[O;H2:8]',
        A=10000000000.0, Ea=100000.0,
        reversible=False, phase='gas',
        alpha=0.0, orders=(1.0, 0.0, 1.0, 0.0, 0.0),
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'claus_comproportionation': TemplateRecord(
        name='claus_comproportionation',
        tier='family',
        catalog_classes=('comproportionation',),
        source='Ea band 40-70 kJ/mol, the catalytic Claus stage over alumina',
        notes='declared orders: first in H2S, first in SO2; the written stoichiometry is global; the SO2 slot is OX1/SX2 because [O]=[S]=[O] also matches a SULFATE, and eight slots over three matching species is 6561 rewrites of a 24-molecule template -- 16 minutes, the day H2S first existed',
        smarts='[S;H2:1].[S;H2:2].[S;H2:3].[S;H2:4].[S;H2:5].[S;H2:6].[S;H2:7].[S;H2:8].[S;H2:9].[S;H2:10].[S;H2:11].[S;H2:12].[S;H2:13].[S;H2:14].[S;H2:15].[S;H2:16].[OX1:100]=[SX2;H0:17]=[OX1:101].[OX1:102]=[SX2;H0:18]=[OX1:103].[OX1:104]=[SX2;H0:19]=[OX1:105].[OX1:106]=[SX2;H0:20]=[OX1:107].[OX1:108]=[SX2;H0:21]=[OX1:109].[OX1:110]=[SX2;H0:22]=[OX1:111].[OX1:112]=[SX2;H0:23]=[OX1:113].[OX1:114]=[SX2;H0:24]=[OX1:115]>>[S;H0:1]1[S;H0:2][S;H0:3][S;H0:4][S;H0:5][S;H0:6][S;H0:7][S;H0:8]1.[S;H0:9]1[S;H0:10][S;H0:11][S;H0:12][S;H0:13][S;H0:14][S;H0:15][S;H0:16]1.[S;H0:17]1[S;H0:18][S;H0:19][S;H0:20][S;H0:21][S;H0:22][S;H0:23][S;H0:24]1.[O;H2:100].[O;H2:101].[O;H2:102].[O;H2:103].[O;H2:104].[O;H2:105].[O;H2:106].[O;H2:107].[O;H2:108].[O;H2:109].[O;H2:110].[O;H2:111].[O;H2:112].[O;H2:113].[O;H2:114].[O;H2:115]',
        A=1000000000.0, Ea=50000.0,
        reversible=False, phase='gas',
        alpha=0.0, orders=(1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'hydroformylation_linear': TemplateRecord(
        name='hydroformylation_linear',
        tier='family',
        catalog_classes=('hydroformylation',),
        source='Ea band 85-125 kJ/mol, Natta apparent barrier for cobalt hydroformylation (~23 kcal/mol)',
        notes='races the branched template; the pair is what makes n:iso a rate ratio',
        smarts='[CX3H2:1]=[CX3:2].[C-:3]#[O+:4].[H:5][H:6]>>[C:1]([C+0:3](=[O+0:4])[H:6])[C:2][H:5]',
        A=100000000000.0, Ea=96000.0,
        reversible=True, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst='cobalt', electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'hydroformylation_branched': TemplateRecord(
        name='hydroformylation_branched',
        tier='family',
        catalog_classes=('hydroformylation',),
        source='Ea 4.8 kJ/mol above the linear route, THE ONLY FITTED NUMBER in this pair, set to the reported n:iso',
        notes='the fit is declared rather than hidden in an alpha',
        smarts='[CX3H2:1]=[CX3:2].[C-:3]#[O+:4].[H:5][H:6]>>[C:1]([H:5])[C:2][C+0:3](=[O+0:4])[H:6]',
        A=100000000000.0, Ea=100800.0,
        reversible=True, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst='cobalt', electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'wacker_oxidation': TemplateRecord(
        name='wacker_oxidation',
        tier='family',
        catalog_classes=('wacker-oxidation',),
        source='Ea band 55-80 kJ/mol, aqueous PdCl2/CuCl2 oxidation of ethylene',
        notes='declared orders; the copper(II) catalyst is an ION, so the network needs electrolyte_provider()',
        smarts='[CH2:1]=[CH2:2].[CH2:3]=[CH2:4].[OX1:5]=[OX1:6].[Cu+2:99]>>[CH3:1][CH1:2]=[O:5].[CH3:3][CH1:4]=[O:6].[Cu+2:99]',
        A=10000000000.0, Ea=65000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=(1.0, 0.0, 1.0, 1.0),
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'skraup_cyclisation': TemplateRecord(
        name='skraup_cyclisation',
        tier='family',
        catalog_classes=('skraup-cyclisation',),
        source='Ea band 60-90 kJ/mol, acid-catalysed Michael addition then cyclisation',
        notes='declared orders; A is the declared 3e6 divided by CATALYST_REFERENCE = 0.1 for the explicit hydronium',
        smarts='[N;H2;+0:1][c:2]1[c;H1:3][c:4][c:5][c:6][c:7]1.[C;H2:8]=[C;H1:9][C;H1:10]=[O;+0:11].[N;H2;+0:13][c:14]1[c;H1:15][c:16][c:17][c:18][c:19]1.[C;H2:20]=[C;H1:21][C;H1:22]=[O;+0:23].[N;H2;+0:25][c:26]1[c;H1:27][c:28][c:29][c:30][c:31]1.[C;H2:32]=[C;H1:33][C;H1:34]=[O;+0:35].[O;+0:41]=[N;+1:40]([O;-1:42])[c:43]1[c:44][c:45][c:46][c:47][c:48]1.[OH3+:99]>>[n;+0:1]1[c;H1:8][c;H1:9][c;H1:10][c;H0:3]2[c:4][c:5][c:6][c:7][c;H0:2]12.[O;H2;+0:11].[n;+0:13]1[c;H1:20][c;H1:21][c;H1:22][c;H0:15]2[c:16][c:17][c:18][c:19][c;H0:14]12.[O;H2;+0:23].[n;+0:25]1[c;H1:32][c;H1:33][c;H1:34][c;H0:27]2[c:28][c:29][c:30][c:31][c;H0:26]12.[O;H2;+0:35].[N;H2;+0:40][c:43]1[c:44][c:45][c:46][c:47][c:48]1.[O;H2;+0:41].[O;H2;+0:42].[OH3+:99]',
        A=30000000.0, Ea=80000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=(1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0),
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'alkene_isomerisation': TemplateRecord(
        name='alkene_isomerisation',
        tier='family',
        catalog_classes=('alkene-isomerisation',),
        source='Ea band 90-120 kJ/mol, base-catalysed allyl to propenyl migration on an arene',
        notes='the hydroxide catalyst is written into both sides of the SMARTS, so it cancels out of K',
        smarts='[c:1][CH2:2][CH1:3]=[CH2:4].[OH-:99]>>[c:1][CH1:2]=[CH1:3][CH3:4].[OH-:99]',
        A=10000000000.0, Ea=115000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'oxidative_cleavage': TemplateRecord(
        name='oxidative_cleavage',
        tier='family',
        catalog_classes=('oxidative-cleavage',),
        source='Ea band 60-90 kJ/mol, alkaline aerobic side-chain cleavage of a propenyl arene; 85 kJ/mol is a CALIBRATION, set so the intermediate never accumulates',
        notes='irreversible: ln K is +94.4 at 470 K',
        smarts='[c:1][CH1:2]=[CH1:3][#6:4].[OX1:5]=[OX1:6]>>[c:1][CH1:2]=[O:5].[#6:4][CH1:3]=[O:6]',
        A=1000000000.0, Ea=85000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'ethanolic_fermentation': TemplateRecord(
        name='ethanolic_fermentation',
        tier='family',
        catalog_classes=(),
        source='Ea 55 kJ/mol, the apparent barrier of a batch fermentation (a Q10 of ~2 near 310 K); A FITTED per branch to the batch time and the solvent slate',
        notes='selectivity between metabolic branches is fitted, not derived; selectivity between chemical templates is derived',
        smarts='[OX2H:1][CH2:2][CH:3]1[OX2:4][CH:5]([OX2H:6])[CH:7]([OX2H:8])[CH:9]([OX2H:10])[CH:11]1[OX2H:12]>>[CH3:5][CH2:7][OH:8].[CH3:2][CH2:3][OH:4].[O:6]=[C:9]=[O:10].[O:1]=[C:11]=[O:12]',
        A=1200.0, Ea=55000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'butanolic_fermentation': TemplateRecord(
        name='butanolic_fermentation',
        tier='family',
        catalog_classes=(),
        source='Ea 55 kJ/mol as ethanolic_fermentation; A FITTED to the ABE solvent slate',
        notes='',
        smarts='[OX2H:1][CH2:2][CH:3]1[OX2:4][CH:5]([OX2H:6])[CH:7]([OX2H:8])[CH:9]([OX2H:10])[CH:11]1[OX2H:12]>>[CH3:2][CH2:3][CH2:5][CH2:7][OH:8].[O:6]=[C:9]=[O:10].[O:1]=[C:11]=[O:12].[OH2:4]',
        A=9000.0, Ea=55000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'acetonic_fermentation': TemplateRecord(
        name='acetonic_fermentation',
        tier='family',
        catalog_classes=('solventogenic-fermentation',),
        source='Ea 55 kJ/mol as ethanolic_fermentation; A FITTED to the ABE solvent slate',
        notes='the fermentation gas CO2:H2 falls out at 62:38 and was NOT fitted',
        smarts='[OX2H:1][CH2:2][CH:3]1[OX2:4][CH:5]([OX2H:6])[CH:7]([OX2H:8])[CH:9]([OX2H:10])[CH:11]1[OX2H:12].[OX2H2:13]>>[CH3:2][CH0:3](=[O:4])[CH3:5].[O:8]=[C:7]=[O:6].[O:10]=[C:9]=[O:1].[O:12]=[C:11]=[O:13].[H][H].[H][H].[H][H].[H][H]',
        A=140.0, Ea=55000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'homolactic_fermentation': TemplateRecord(
        name='homolactic_fermentation',
        tier='family',
        catalog_classes=('homolactic-fermentation',),
        source='Ea 55 kJ/mol as ethanolic_fermentation; A FITTED to the batch time',
        notes='',
        smarts='[OX2H:1][CH2:2][C;H1;@,@@:3]1[OX2:4][C;H1;@,@@:5]([OX2H:6])[C;H1;@,@@:7]([OX2H:8])[C;H1;@,@@:9]([OX2H:10])[C;H1;@,@@:11]1[OX2H:12]>>[CH3:5][CH1:7]([OH:8])[CH0:9](=[O:10])[OH:6].[CH3:2][CH1:3]([OH:4])[CH0:11](=[O:12])[OH:1]',
        A=1000.0, Ea=55000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'ketofuranose_dehydration': TemplateRecord(
        name='ketofuranose_dehydration',
        tier='family',
        catalog_classes=('dehydration-cyclisation',),
        source='Ea band 125-160 kJ/mol, fructose dehydration in dilute aqueous mineral acid',
        notes='must stay ABOVE the aldose route: the ordering is the selectivity',
        smarts='[OX2H:1][CH2:2][C;H1;@,@@:3]1[OX2:4][C;@,@@:5]([OX2H:6])([CH2:7][OX2H:8])[C;H1;@,@@:9]([OX2H:10])[C;H1;@,@@:11]1[OX2H:12]>>[OH1:8][CH2:7][CH0:5]1=[CH1:9][CH1:11]=[CH0:3]([CH1:2]=[OH0:1])[OH0:4]1.[OH2:6].[OH2:10].[OH2:12]',
        A=10000000000000.0, Ea=140000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'aldofuranose_dehydration': TemplateRecord(
        name='aldofuranose_dehydration',
        tier='family',
        catalog_classes=('dehydration-cyclisation',),
        source='Ea band 120-145 kJ/mol, xylose dehydration in dilute mineral acid',
        notes='',
        smarts='[OX2H:1][CH2:2][C;H1;@,@@:3]1[OX2:4][C;H1;@,@@:5]([OX2H:6])[C;H1;@,@@:7]([OX2H:8])[C;H1;@,@@:9]1[OX2H:10]>>[OH0:6]=[CH1:5][CH0:7]1=[CH1:9][CH1:3]=[CH1:2][OH0:1]1.[OH2:4].[OH2:8].[OH2:10]',
        A=10000000000000.0, Ea=130000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'hydroxymethylfurfural_rehydration': TemplateRecord(
        name='hydroxymethylfurfural_rehydration',
        tier='family',
        catalog_classes=('hydration-ring-opening',),
        source='Ea 110 kJ/mol; Girisuta et al. report 110.5 kJ/mol for HMF decomposition',
        notes='the loss pathway that makes the furan yield a yield',
        smarts='[OX2H:1][CH2:2][c:3]1[cH:4][cH:5][c:6]([CH:7]=[O:8])[o:9]1.[OX2H2:10].[OX2H2:11]>>[CH3:2][CH0:3](=[OH0:1])[CH2:4][CH2:5][CH0:6](=[OH0:9])[OH1:10].[CH1:7](=[OH0:8])[OH1:11]',
        A=500000.0, Ea=110000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'water_electrolysis': TemplateRecord(
        name='water_electrolysis',
        tier='family',
        catalog_classes=('electro-organic-coupling',),
        source='A = 5e-8 mol/(L s) is a CURRENT DENSITY, j0*a/(nF) = 1e-3*10/(2*96485) for a bench cell; Ea = n F eta_a with eta_a = 0.80 V',
        notes='alpha 0.5 is the Butler-Volmer transfer coefficient, which Evans-Polanyi IS on an electrode',
        smarts='[OX2H2:1].[OX2H2:2]>>[H][H].[H][H].[O:1]=[O:2]',
        A=5e-08, Ea=308753.062784,
        reversible=True, phase='liquid',
        alpha=0.5, orders=None,
        solid_catalyst=None, electrons=4,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'halide_electrolysis': TemplateRecord(
        name='halide_electrolysis',
        tier='family',
        catalog_classes=('aqueous-electrolysis',),
        source='A as water_electrolysis; Ea = n F eta_a with eta_a = 0.40 V',
        notes='the LOWER overpotential is why brine evolves chlorine rather than the oxygen its thermodynamics prefers',
        smarts='[Cl,Br,I;-1:1].[Cl,Br,I;-1:2].[OX2H2:3].[OX2H2:4]>>[*;+0:1][*;+0:2].[OH-:3].[OH-:4].[H][H]',
        A=5e-08, Ea=77188.265696,
        reversible=True, phase='liquid',
        alpha=0.5, orders=None,
        solid_catalyst=None, electrons=2,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'kolbe_electrolysis': TemplateRecord(
        name='kolbe_electrolysis',
        tier='family',
        catalog_classes=('electro-organic-coupling',),
        source='A as water_electrolysis; Ea = n F eta_a with eta_a = 1.20 V',
        notes='one A for all four electrode templates, deliberately: the selectivity must come from the barrier',
        smarts='[#6:1][CX3:2](=[O:3])[O-:4].[#6:5][CX3:6](=[O:7])[O-:8].[OX2H2:9].[OX2H2:10]>>[#6:1][#6:5].[O:3]=[C;+0:2]=[O;+0:4].[O:7]=[C;+0:6]=[O;+0:8].[OH-:9].[OH-:10].[H][H]',
        A=5e-08, Ea=231564.79708800002,
        reversible=True, phase='liquid',
        alpha=0.5, orders=None,
        solid_catalyst=None, electrons=2,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'alkene_hydrodimerisation': TemplateRecord(
        name='alkene_hydrodimerisation',
        tier='family',
        catalog_classes=('electro-organic-coupling',),
        source='Ea 55 kJ/mol; A 1e8 as an ordinary bimolecular liquid-phase step',
        notes='electrons=0: the coupling itself is chemistry, driven by an electrode reaction elsewhere in the cell',
        smarts='[CH2:1]=[CH1:2][C:3]#[N:4].[CH2:5]=[CH1:6][C:7]#[N:8].[H][H]>>[N:4]#[C:3][CH2:2][CH2:1][CH2:5][CH2:6][C:7]#[N:8]',
        A=100000000.0, Ea=55000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'water_autoionization': TemplateRecord(
        name='water_autoionization',
        tier='family',
        catalog_classes=('proton-transfer', 'acid-displacement', 'acid-displacement-precipitating'),
        source='A 1e12 and Ea 60 kJ/mol for all six: proton transfer is diffusion limited. Ea sits just above the largest dissociation enthalpy in the table (water, 55.8 kJ/mol) so the elementary-barrier clamp does not fire',
        notes='no pKa is declared here; it enters through the ion thermochemistry and detailed balance',
        smarts='[OX2H2:1].[OX2H2:2]>>[OH3+:1].[OH-:2]',
        A=1000000000000.0, Ea=60000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'carboxylic_acid_dissociation': TemplateRecord(
        name='carboxylic_acid_dissociation',
        tier='family',
        catalog_classes=('proton-transfer', 'acid-displacement', 'acid-displacement-precipitating'),
        source='A and Ea as water_autoionization',
        notes='',
        smarts='[CX3:1](=[O:2])[OX2H1:3].[OX2H2:4]>>[CX3:1](=[O:2])[O-:3].[OH3+:4]',
        A=1000000000000.0, Ea=60000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'phenol_dissociation': TemplateRecord(
        name='phenol_dissociation',
        tier='family',
        catalog_classes=('proton-transfer', 'acid-displacement', 'acid-displacement-precipitating'),
        source='A and Ea as water_autoionization',
        notes='covers williamson-ether step 1, whose row reads phenol + NaOH -> sodium-phenoxide despite its name',
        smarts='[c:1][OX2H1:2].[OX2H2:3]>>[c:1][O-:2].[OH3+:3]',
        A=1000000000000.0, Ea=60000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'hydrogen_halide_dissociation': TemplateRecord(
        name='hydrogen_halide_dissociation',
        tier='family',
        catalog_classes=('proton-transfer', 'acid-displacement', 'acid-displacement-precipitating'),
        source='A and Ea as water_autoionization',
        notes='',
        smarts='[F,Cl,Br,I;H1:1].[OX2H2:2]>>[F,Cl,Br,I;-:1].[OH3+:2]',
        A=1000000000000.0, Ea=60000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'mineral_oxyacid_dissociation': TemplateRecord(
        name='mineral_oxyacid_dissociation',
        tier='family',
        catalog_classes=('proton-transfer', 'acid-displacement', 'acid-displacement-precipitating'),
        source='A and Ea as water_autoionization',
        notes='',
        smarts='[S,N,P;+0,+1:1](=[O:2])[OX2H1:3].[OX2H2:4]>>[S,N,P:1](=[O:2])[O-:3].[OH3+:4]',
        A=1000000000000.0, Ea=60000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'amine_protonation': TemplateRecord(
        name='amine_protonation',
        tier='family',
        catalog_classes=('proton-transfer', 'acid-displacement', 'acid-displacement-precipitating'),
        source='A and Ea as water_autoionization',
        notes='written in the PROTONATION direction because discovery once ran templates forward only; T7 sweeps a reversible template from both sides, so the direction is now a choice rather than a constraint',
        smarts='[NX3;!$([N+]);!$([NX3][CX3]=O);!$([NX3]=*);!$([NX3]#*):1].[OH3+:2]>>[NX4+:1].[OX2H2;+0:2]',
        A=1000000000000.0, Ea=60000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'sulfide_protonation': TemplateRecord(
        name='sulfide_protonation',
        tier='family',
        catalog_classes=('proton-transfer', 'acid-displacement', 'acid-displacement-precipitating'),
        source='A and Ea as water_autoionization',
        notes='pKa 12.91, derived in properties/electrolyte; it is what lets a metal sulfide be charged ion by ion',
        smarts='[S;H0;-2:1].[OH3+:2]>>[S;H1;-1:1].[OX2H2;+0:2]',
        A=1000000000000.0, Ea=60000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'hydrosulfide_protonation': TemplateRecord(
        name='hydrosulfide_protonation',
        tier='family',
        catalog_classes=('proton-transfer', 'acid-displacement', 'acid-displacement-precipitating'),
        source='A and Ea as water_autoionization',
        notes="written in the protonation direction, as amine_protonation is: the reverse sweep's no-building-up bound refuses a proton, so a dissociation-direction row could never protonate a sulfide. H2S only, not a thiol: a thiolate has no pKa row",
        smarts='[S;H1;-1:1].[OH3+:2]>>[S;H2;+0:1].[OX2H2;+0:2]',
        A=1000000000000.0, Ea=60000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'methane_ammoxidation': TemplateRecord(
        name='methane_ammoxidation',
        tier='family',
        catalog_classes=('ammoxidation',),
        source='A is the gas termolecular order-of-magnitude choice and is rescaled by SOLID_CATALYST_REFERENCE; Ea is a band midpoint picked so the rewrite needs the 1400 K the catalog step declares',
        notes='one O2 and an H2 by-product is the only integral balance for CH4 + NH3 + O2 at these slot counts, and Andrussow off-gas does carry hydrogen; HCN has no thermochemistry, so build_network discards the rewrite and reports it unpriced',
        smarts='[CX4;H4:1].[NX3;H3:2].[OX1:3]=[OX1:4]>>[CH1:1]#[N:2].[OX2H2:3].[OX2H2:4].[H][H]',
        A=10000000000.0, Ea=160000.0,
        reversible=False, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst='platinum', electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'allylic_ammoxidation': TemplateRecord(
        name='allylic_ammoxidation',
        tier='family',
        catalog_classes=('ammoxidation',),
        source='A as methane_ammoxidation; Ea a band midpoint picked so the rewrite needs the 720 K the SOHIO step declares',
        notes="the Bi-Mo oxide is in the step's conditions and not among its species, so no solid_catalyst is declared; the two byproduct steps of acrylonitrile-sohio are C-C scission and are not this mechanism",
        smarts='[CX4;H3:1][CX3:5]=[CX3:6].[NX3;H3:2].[OX1:3]=[OX1:4]>>[N:2]#[CH0:1][C:5]=[C:6].[OX2H2:3].[OX2H2:4].[H][H]',
        A=10000000000.0, Ea=90000.0,
        reversible=False, phase='gas',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'intramolecular_williamson': TemplateRecord(
        name='intramolecular_williamson',
        tier='family',
        catalog_classes=('intramolecular-williamson',),
        source='A the liquid bimolecular order-of-magnitude choice; Ea the midpoint of the SN2 band, which puts the ring closure at the 340-370 K the three steps declare',
        notes='irreversible: chloride ring-opens an epoxide only under acid, and all three steps run in lime or caustic. All three report partial because each declares its salt as one species where the engine holds the ions',
        smarts='[OX2H1:1][CX4:2][CX4:3][F,Cl,Br,I:4].[OH-:5]>>[OH0:1]1[C:2][C:3]1.[*-:4].[OX2H2;+0:5]',
        A=100000000.0, Ea=60000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'alcohol_halide_substitution': TemplateRecord(
        name='alcohol_halide_substitution',
        tier='family',
        catalog_classes=('nucleophilic-substitution',),
        source='A the liquid bimolecular order-of-magnitude choice; Ea a band midpoint above the SN2 band because the leaving group is an unassisted hydroxyl',
        notes='reversible: the reverse is the hydrolysis of an alkyl halide, which is a reaction somebody runs',
        smarts='[CX4:1][OX2H1:2].[F,Cl,Br,I;H1:3]>>[C:1][*:3].[OX2H2:2]',
        A=100000000.0, Ea=80000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'carbanion_alkylation': TemplateRecord(
        name='carbanion_alkylation',
        tier='family',
        catalog_classes=('nucleophilic-substitution',),
        source='A the liquid bimolecular order-of-magnitude choice; Ea the midpoint of the SN2 band, which puts the alkylation at the reflux the two ester-synthesis steps declare',
        notes='irreversible: the new C-C bond is not cleaved by halide. The carbanion itself comes from carbanion-generation, which is a separate uncovered class',
        smarts='[CX3;-1:1].[CX4:2][F,Cl,Br,I:3]>>[C;+0:1][C:2].[*-:3]',
        A=100000000.0, Ea=50000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'amide_methylolation': TemplateRecord(
        name='amide_methylolation',
        tier='family',
        catalog_classes=('nucleophilic-addition',),
        source='A two decades below the liquid bimolecular choice because the step is base-catalysed and no base is written into the SMARTS; Ea a band midpoint at the 330 K the step declares',
        notes='the nucleophile is an AMIDE nitrogen, not any primary amine: an amine plus an aldehyde does not stop at the carbinolamine, it dehydrates to the imine, which is the separate imine-formation class. Widening the slot to [NX3;H2] took a urea-plus-formaldehyde flask from 2 reactions to 122',
        smarts='[CX3;H1,H2:1]=[OX1:2].[NX3;H2:3][CX3:7]=[OX1:8]>>[C:1]([NH1:3][C:7]=[O:8])[OX2H1:2]',
        A=1000000.0, Ea=50000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'ketene_acid_addition': TemplateRecord(
        name='ketene_acid_addition',
        tier='family',
        catalog_classes=('nucleophilic-addition',),
        source='A the liquid bimolecular order-of-magnitude choice; Ea a low band midpoint because the ketene is a transient and the absorber runs at 320 K',
        notes='irreversible: the anhydride does not give a ketene back at 320 K',
        smarts='[CH2X3:1]=[CX2:2]=[OX1:3].[CX3:4](=[OX1:5])[OX2H1:6]>>[CH3:1][C:2](=[O:3])[O:6][C:4]=[O:5]',
        A=100000000.0, Ea=30000.0,
        reversible=False, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
    'cyanide_imine_addition': TemplateRecord(
        name='cyanide_imine_addition',
        tier='family',
        catalog_classes=('nucleophilic-addition',),
        source='A the liquid bimolecular order-of-magnitude choice; Ea a band midpoint at the ambient the Strecker step declares',
        notes='reversible: an aminonitrile reverting to its imine and HCN is the equilibrium the Strecker sequence is run to beat. Silent in the engine today for the same reason as methane_ammoxidation -- HCN has no thermochemistry, so build_network discards the rewrite and reports it unpriced',
        smarts='[CX3:1]=[NX2;H1:2].[CX2;H1:3]#[NX1:4]>>[C:1]([NH2:2])[CH0:3]#[N:4]',
        A=100000000.0, Ea=40000.0,
        reversible=True, phase='liquid',
        alpha=0.0, orders=None,
        solid_catalyst=None, electrons=0,
        hammett_rho=0.0, hammett_slot=0,
        hammett_saturation=2.686,
    ),
}


def load_templates(
    tier: str = "family",
    classes: tuple[str, ...] | None = None,
) -> list[ReactionTemplate]:
    """The templates of one tier, optionally narrowed to some catalog classes.

    ``tier`` defaults to ``"family"`` and that default is load-bearing: it is
    what keeps an extracted literal row out of a flask that did not ask for one.
    Pass ``tier="any"`` to load every row, which is a deliberate act.

    ``classes`` narrows to rows carrying at least one of the named
    ``route_steps.psv`` reaction classes.
    """
    out = []
    for rec in TEMPLATES.values():
        if tier != "any" and rec.tier != tier:
            continue
        if classes is not None and not set(rec.catalog_classes) & set(classes):
            continue
        out.append(rec.build())
    return out


def template_classes(tier: str = "any") -> dict[str, tuple[str, ...]]:
    """catalog reaction class -> the template names covering it.

    Several templates may cover one class: that is a class covered by a FAMILY,
    and the credit belongs to the family rather than to a member.
    """
    out: dict[str, list[str]] = {}
    for rec in TEMPLATES.values():
        if tier != "any" and rec.tier != tier:
            continue
        for cls in rec.catalog_classes:
            out.setdefault(cls, []).append(rec.name)
    return {c: tuple(n) for c, n in sorted(out.items())}


def tier_counts() -> dict[str, int]:
    """How many rows per tier -- COUNTED, so a report cannot assert it."""
    out: dict[str, int] = {}
    for rec in TEMPLATES.values():
        out[rec.tier] = out.get(rec.tier, 0) + 1
    return dict(sorted(out.items()))
