"""Layer 1 -- parameters for the Wilson-Jasperson and Fedors methods.

GENERATED by ``tools/build_physical_data.py`` from ``thermo`` 0.6.1 (MIT).
Do not hand-edit: regenerate.

These two methods exist here for one reason. Joback covers Tb/Tc/Pc/Vc but
refuses any molecule his groups cannot partition, and Benson -- the better
estimator sitting above him -- says nothing about critical properties at all,
because group additivity is a statement about formation quantities. So a species
Joback cannot fragment had no physical half available from anywhere, and its
Benson formation half was unreachable however good it was.

**Wilson-Jasperson takes Tb as an INPUT**, which is what makes the pair useful:
supply a boiling point and Tc and Pc follow, and Fedors gives Vc from structure
alone. That collapses the whole coverage problem to one lookup.

Accuracy, measured on acetic anhydride against CRC:

    Tc  600.9 vs 606.0 K      0.8%
    Pc   44.9 vs  40.0 bar   12%    <-- the weak number in the chain
    Vc  290.3 vs 294.0 cm3    1.3%

Pc is the one to watch. It feeds the acentric factor (derived by inverting
Lee-Kesler at Tb), which sets the entire vapour-pressure curve, so every entry
enabled by this route has to pass the boils-at-1-atm cross-check in
``validation/physical_estimation.py``.
"""

from __future__ import annotations

# --- Wilson-Jasperson ------------------------------------------------------
# Zero-order: per-ELEMENT increments, summed over the whole formula including
# hydrogen. ``None`` in the Pc table means the element was never regressed;
# that must refuse the estimate, not contribute zero.
WJ_TC_INCREMENTS: dict[str, float] = {
    'H': 0.002793,
    'D': 0.002793,
    'T': 0.002793,
    'He': 0.32,
    'B': 0.019,
    'C': 0.008532,
    'N': 0.019181,
    'O': 0.020341,
    'F': 0.00881,
    'Ne': 0.0364,
    'Al': 0.088,
    'Si': 0.02,
    'P': 0.012,
    'S': 0.007271,
    'Cl': 0.011151,
    'Ar': 0.0168,
    'Ti': 0.014,
    'V': 0.0186,
    'Ga': 0.059,
    'Ge': 0.031,
    'As': 0.007,
    'Se': 0.0103,
    'Br': 0.012447,
    'Kr': 0.0133,
    'Rb': -0.027,
    'Zr': 0.175,
    'Nb': 0.0176,
    'Mo': 0.007,
    'Sn': 0.02,
    'Sb': 0.01,
    'Te': 0,
    'I': 0.0059,
    'Xe': 0.017,
    'Cs': -0.0275,
    'Hf': 0.219,
    'Ta': 0.013,
    'W': 0.011,
    'Re': 0.014,
    'Os': -0.05,
    'Hg': 0,
    'Bi': 0,
    'Rn': 0.007,
    'U': 0.015,
}

WJ_PC_INCREMENTS: dict[str, float | None] = {
    'H': 0.1266,
    'D': 0.1266,
    'T': 0.1266,
    'He': 0.434,
    'B': 0.91,
    'C': 0.72983,
    'N': 0.44805,
    'O': 0.4336,
    'F': 0.32868,
    'Ne': 0.126,
    'Al': 6.05,
    'Si': 1.34,
    'P': 1.22,
    'S': 1.04713,
    'Cl': 0.97711,
    'Ar': 0.796,
    'Ti': 1.19,
    'V': None,
    'Ga': None,
    'Ge': 1.42,
    'As': 2.68,
    'Se': 1.2,
    'Br': 0.97151,
    'Kr': 1.11,
    'Rb': None,
    'Zr': 1.11,
    'Nb': 2.71,
    'Mo': 1.69,
    'Sn': 1.95,
    'Sb': None,
    'Te': 0.43,
    'I': 1.31593,
    'Xe': 1.66,
    'Cs': 6.33,
    'Hf': 1.07,
    'Ta': None,
    'W': 1.08,
    'Re': None,
    'Os': None,
    'Hg': -0.08,
    'Bi': 0.69,
    'Rn': 2.05,
    'U': 2.04,
}

# Second-order: functional-group corrections on top of the element sums.
WJ_TC_GROUPS: dict[str, float] = {
    'OH_large': 0.01,
    'OH_small': 0.035,
    '-O-': -0.0075,
    'amine': -0.004,
    '-CHO': 0,
    '>CO': -0.055,
    '-COOH': 0.017,
    '-COO-': -0.015,
    '-CN': 0.017,
    '-NO2': -0.02,
    'halide': 0.002,
    'sulfur_groups': 0.0,
    'siloxane': -0.025,
}

WJ_PC_GROUPS: dict[str, float] = {
    'OH_large': 0,
    'OH_small': 0,
    '-O-': 0,
    'amine': 0,
    '-CHO': 0.5,
    '>CO': 0,
    '-COOH': 0.5,
    '-COO-': 0,
    '-CN': 1.5,
    '-NO2': 1.0,
    'halide': 0,
    'sulfur_groups': 0.0,
    'siloxane': -0.5,
}

# The SMARTS that count those groups. ``OH`` is split into ``OH_small`` and
# ``OH_large`` at match time by carbon count (< 5 vs >= 5), which is why one
# pattern serves two table keys.
WJ_GROUP_SMARTS: dict[str, str | tuple[str, ...]] = {
    'OH': '[#6][OX2H]',
    '-O-': '[OD2]([#6])[#6]',
    'amine': ('[NX3+0,NX4+;!$([N]~[!#6]);!$([N]*~[#7,#8,#15,#16])]', '[ND3]([CX4])([CX4])[CX4]', '[NX3H0+0,NX4H1+;!$([N][!c]);!$([N]*~[#7,#8,#15,#16])]', '[NX3H0+0,NX4H1+;!$([N][!C]);!$([N]*~[#7,#8,#15,#16])]', '[NX3H0+0,NX4H1+;$([N]([c])([C])[#6]);!$([N]*~[#7,#8,#15,#16])]', '[#6]-[#7](-[#6])-[#6]', '[CX4][NH2]', '[NX3H2+0,NX4H3+;!$([N][!C]);!$([N]*~[#7,#8,#15,#16])]', '[NX3H2+0,NX4H3+]c', '[N+X4]([c,C])([c,C])([c,C])[c,C]'),
    '-CHO': '[CX3H1](=O)[#6]',
    '>CO': '[#6][CX3](=O)[#6]',
    '-COOH': '[CX3](=O)[OX2H1]',
    '-COO-': '[OX2H0][#6;!$([C]=[O])]',
    '-CN': '[NX1]#[CX2]',
    '-NO2': '[$([NX3](=O)=O),$([NX3+](=O)[O-])][!#8]',
    'halide': '[#6][F,Cl,Br,I]',
    'sulfur_groups': ('[#16X2H]', '[!#16][#16X2H0][!#16]', '[#16X2H0][#16X2H0]'),
    'siloxane': '[Si][O][Si]',
}

# --- Fedors ----------------------------------------------------------------
# Vc = 26.6 + sum(contributions), in cm3/mol. Atom counts include hydrogen;
# ring terms are per ring of that size; ``ring_ring_bonds`` counts rings bonded
# to another ring.
FEDORS_BASE: float = 26.6

FEDORS_CONTRIBUTIONS: dict[str, float] = {
    'C': 34.426,
    'H': 9.172,
    'O': 20.291,
    'O_alcohol': 18,
    'N': 48.855,
    'N_amine': 47.422,
    'F': 22.242,
    'Cl': 52.801,
    'Br': 71.774,
    'I': 96.402,
    'S': 50.866,
    '3_ring': -15.824,
    '4_ring': -17.247,
    '5_ring': -39.126,
    '6_ring': -39.508,
    'double_bond': 5.028,
    'triple_bond': 0.7973,
    'ring_ring_bonds': 35.524,
}

# Outside this set Fedors has no increment, and the published method reports
# "errors found" rather than a number. That signal is kept -- it is the same
# discipline this project uses everywhere, and glyphosate's phosphorus is
# exactly the case it exists for.
FEDORS_ALLOWED_ATOMS: frozenset[str] = frozenset(['Br', 'C', 'Cl', 'F', 'H', 'I', 'N', 'O', 'S'])

# Matched against the EXPLICIT-hydrogen graph, which changes what they mean.
# See ``tools/build_physical_data.py`` Trap 2: ``amine_smarts`` carries
# ``!$([N]~[!#6])``, and with hydrogens as real atoms an N-H bond satisfies
# ``[!#6]``, so only tertiary amines match. This reproduces ``thermo``'s
# behaviour exactly so the oracle test is exact; the cost is 1.4 cm3/mol per
# amine nitrogen classified the other way.
FEDORS_GROUP_SMARTS: dict[str, str] = {
    'O_alcohol': '[#6][OX2H]',
    'N_amine': '[NX3+0,NX4+;!$([N]~[!#6]);!$([N]*~[#7,#8,#15,#16])]',
}
