"""Layer 1 data -- relative permittivity per liquid, and van der Waals radii.

⚠ GENERATED by ``tools/build_dielectric_data.py``. Do not hand-edit: re-run the
tool. Every value below is transcribed from an external source with its
provenance and, where it has one, its validity window.

``PERMITTIVITY`` maps canonical SMILES to ``(coeffs, T_range, kind, source)``
where ``coeffs`` is ``eps(T) = a + bT + cT^2 + dT^3`` -- the same polynomial
basis this project already evaluates for liquid molar volume and heat capacity,
so nothing here is fitted or refitted.

``kind`` is ``"polynomial"`` for a CRC correlation and ``"single point"`` for a
lone measurement held constant, and the distinction is not cosmetic: a constant
permittivity has no temperature slope, and every real liquid's falls as it warms.

``VDW_RADII`` is per ELEMENT, in angstrom, and feeds only the DERIVED tier of
``properties/dielectric.ionic_radius`` -- the curated ionic radii are a separate
table in that module, because this source has none.
"""

from __future__ import annotations

PERMITTIVITY: dict[str, tuple[tuple[float, float, float, float], tuple[float, float], str, str]] = {
    # formamide [75-12-7] -- eps(298 K) = 108.943
    'NC=O': (
        (260.76, -0.61145, 0.00034296, 0.0),
        (278.0, 333.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # water [7732-18-5] -- eps(298 K) = 78.355
    'O': (
        (249.21, -0.79069, 0.00072997, 0.0),
        (273.0, 372.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # hydrogen peroxide [7722-84-1] -- eps(298 K) = 70.789
    'OO': (
        (485.11, -2.3145, 0.003102, 0.0),
        (233.0, 303.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # formic acid [64-18-6] -- eps(298 K) = 51.591
    'O=CO': (
        (140.4, -0.24673, -0.00017151, 0.0),
        (287.0, 358.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # dimethyl sulfoxide [67-68-5] -- eps(298 K) = 46.826
    'CS(C)=O': (
        (38.478, 0.16939, -0.00047423, 0.0),
        (288.0, 343.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # glycerol [56-81-5] -- eps(298 K) = 45.637
    'OCC(O)CO': (
        (77.503, -0.037984, -0.00023107, 0.0),
        (288.0, 343.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # furfural [98-01-1] -- eps(298 K) = 42.100
    'O=Cc1ccco1': (
        (42.1, 0.0, 0.0, 0.0),
        (293.2, 293.2),
        'single point',
        'CRC Handbook single measured value at 293.2 K (via chemicals 1.5.2), held constant',
    ),
    # ethylene glycol [107-21-1] -- eps(298 K) = 40.245
    'OCCO': (
        (143.55, -0.48573, 0.00046703, 0.0),
        (293.0, 423.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # N,N-dimethylformamide [68-12-2] -- eps(298 K) = 37.219
    'CN(C)C=O': (
        (153.64, -0.60367, 0.00071505, 0.0),
        (213.0, 353.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # nitromethane [75-52-5] -- eps(298 K) = 36.562
    'C[N+](=O)[O-]': (
        (112.27, -0.35591, 0.00034206, 0.0),
        (288.0, 343.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # acetonitrile [75-05-8] -- eps(298 K) = 35.688
    'CC#N': (
        (297.24, -1.5508, 0.0022591, 0.0),
        (288.0, 333.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # nitrobenzene [98-95-3] -- eps(298 K) = 34.809
    'O=[N+]([O-])c1ccccc1': (
        (112.12, -0.35211, 0.00031128, 0.0),
        (279.0, 533.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # methanol [67-56-1] -- eps(298 K) = 32.613
    'CO': (
        (193.41, -0.92211, 0.0012839, 0.0),
        (177.0, 293.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # ethanol [64-17-5] -- eps(298 K) = 24.852
    'CCO': (
        (151.45, -0.8702, 0.001957, -1.5512e-06),
        (163.0, 523.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # acetaldehyde [75-07-0] -- eps(298 K) = 21.000
    'CC=O': (
        (21.0, 0.0, 0.0, 0.0),
        (291.2, 291.2),
        'single point',
        'CRC Handbook single measured value at 291.2 K (via chemicals 1.5.2), held constant',
    ),
    # 1-propanol [71-23-8] -- eps(298 K) = 20.524
    'CCCO': (
        (98.045, -0.3686, 0.00036422, 0.0),
        (193.0, 493.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # acetone [67-64-1] -- eps(298 K) = 20.493
    'CC(C)=O': (
        (88.157, -0.343, 0.00038925, 0.0),
        (273.0, 323.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # 2-propanol [67-63-0] -- eps(298 K) = 19.264
    'CC(C)O': (
        (104.16, -0.41011, 0.00042049, 0.0),
        (193.0, 493.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # propionaldehyde [123-38-6] -- eps(298 K) = 18.500
    'CCC=O': (
        (18.5, 0.0, 0.0, 0.0),
        (290.2, 290.2),
        'single point',
        'CRC Handbook single measured value at 290.2 K (via chemicals 1.5.2), held constant',
    ),
    # 2-butanone [78-93-3] -- eps(298 K) = 18.246
    'CCC(C)=O': (
        (15.457, 0.090152, -0.000271, 0.0),
        (293.0, 333.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # benzaldehyde [100-52-7] -- eps(298 K) = 18.220
    'O=Cc1ccccc1': (
        (35.046, -0.061271, 1.6222e-05, 0.0),
        (301.0, 346.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # 1-butanol [71-36-3] -- eps(298 K) = 17.332
    'CCCCO': (
        (105.78, -0.50587, 0.00084733, -4.8841e-07),
        (193.0, 553.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # ammonia [7664-41-7] -- eps(298 K) = 16.160
    'N': (
        (66.756, -0.24696, 0.00025913, 0.0),
        (238.0, 323.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # pyridine [110-86-1] -- eps(298 K) = 12.978
    'c1ccncc1': (
        (43.991, -0.1515, 0.00015925, 0.0),
        (293.0, 323.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # phenol [108-95-2] -- eps(298 K) = 12.828
    'Oc1ccccc1': (
        (63.391, -0.24988, 0.0002693, 0.0),
        (303.0, 433.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # 2-methyl-2-propanol [75-65-0] -- eps(298 K) = 12.341
    'CC(C)(C)O': (
        (225.41, -1.499, 0.003405, -2.5968e-06),
        (298.0, 503.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # 1,2-dichloroethane [107-06-2] -- eps(298 K) = 10.125
    'ClCCCl': (
        (24.404, -0.047892, 0.0, 0.0),
        (293.0, 343.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # 1-octanol [111-87-5] -- eps(298 K) = 9.863
    'CCCCCCCCO': (
        (51.647, -0.20371, 0.0002132, 0.0),
        (258.0, 513.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # methyl formate [107-31-3] -- eps(298 K) = 8.838
    'COC=O': (
        (19.699, -0.036429, 0.0, 0.0),
        (288.0, 302.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # dichloromethane [75-09-2] -- eps(298 K) = 8.819
    'ClCCl': (
        (40.452, -0.17748, 0.00023942, 0.0),
        (184.0, 306.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # methylamine [74-89-5] -- eps(298 K) = 8.776
    'CN': (
        (34.398, -0.07363, -4.1279e-05, 0.0),
        (198.0, 258.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # ethyl formate [109-94-4] -- eps(298 K) = 8.331
    'CCOC=O': (
        (15.884, -0.025333, 0.0, 0.0),
        (288.0, 318.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # tetrahydrofuran [109-99-9] -- eps(298 K) = 7.426
    'C1CCOC1': (
        (30.739, -0.12946, 0.00017195, 0.0),
        (224.0, 295.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # aniline [62-53-3] -- eps(298 K) = 6.888
    'Nc1ccccc1': (
        (8.9534, 0.003899, -3.631e-05, 0.0),
        (293.0, 413.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # methyl acetate [79-20-9] -- eps(298 K) = 6.861
    'COC(C)=O': (
        (13.19, -0.021226, 0.0, 0.0),
        (276.0, 318.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # methyl benzoate [93-58-3] -- eps(298 K) = 6.737
    'COC(=O)c1ccccc1': (
        (17.486, -0.051027, 5.0222e-05, 0.0),
        (303.0, 393.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # acetic acid [64-19-7] -- eps(298 K) = 6.253
    'CC(=O)O': (
        (-15.731, 0.12662, -0.00017738, 0.0),
        (293.0, 363.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # ethyl benzoate [93-89-0] -- eps(298 K) = 6.102
    'CCOC(=O)c1ccccc1': (
        (18.216, -0.062361, 7.2884e-05, 0.0),
        (288.0, 343.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # ethyl acetate [141-78-6] -- eps(298 K) = 5.987
    'CCOC(C)=O': (
        (15.646, -0.044066, 3.9137e-05, 0.0),
        (293.0, 433.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # chlorobenzene [108-90-7] -- eps(298 K) = 5.697
    'Clc1ccccc1': (
        (19.471, -0.070786, 8.2466e-05, 0.0),
        (293.0, 430.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # chloroform [67-66-3] -- eps(298 K) = 4.711
    'ClC(Cl)Cl': (
        (15.115, -0.05183, 5.6803e-05, 0.0),
        (218.0, 323.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # diethyl ether [60-29-7] -- eps(298 K) = 4.240
    'CCOCC': (
        (7.9725, -0.012519, 0.0, 0.0),
        (283.0, 301.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # propionic acid [79-09-4] -- eps(298 K) = 3.454
    'CCC(=O)O': (
        (1.8793, 0.0046841, 1.9983e-06, 0.0),
        (289.0, 408.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # carbon disulfide [75-15-0] -- eps(298 K) = 2.611
    'S=C=S': (
        (4.5024, -0.012054, 1.9147e-05, 0.0),
        (154.0, 319.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # styrene [100-42-5] -- eps(298 K) = 2.464
    'C=Cc1ccccc1': (
        (4.4473, -0.011422, 1.6e-05, 0.0),
        (293.0, 313.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # triethylamine [121-44-8] -- eps(298 K) = 2.383
    'CCN(CC)CC': (
        (2.9205, -0.0014007, -1.3469e-06, 0.0),
        (233.0, 323.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # toluene [108-88-3] -- eps(298 K) = 2.374
    'Cc1ccccc1': (
        (3.2584, -0.003441, 1.5937e-06, 0.0),
        (207.0, 316.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # m-xylene [108-38-3] -- eps(298 K) = 2.348
    'Cc1cccc(C)c1': (
        (2.8421, -0.0010191, -2.1429e-06, 0.0),
        (273.0, 323.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # benzene [71-43-2] -- eps(298 K) = 2.271
    'c1ccccc1': (
        (2.6706, -0.00091648, -1.4257e-06, 0.0),
        (293.0, 513.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # carbon tetrachloride [56-23-5] -- eps(298 K) = 2.228
    'ClC(Cl)(Cl)Cl': (
        (2.828, -0.0020339, 7.1795e-08, 0.0),
        (283.0, 333.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # 1,4-dioxane [123-91-1] -- eps(298 K) = 2.210
    'C1COCCO1': (
        (2.7299, -0.001744, 0.0, 0.0),
        (293.0, 313.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # cyclohexane [110-82-7] -- eps(298 K) = 2.016
    'C1CCCCC1': (
        (2.4293, -0.0012095, -5.8741e-07, 0.0),
        (283.0, 333.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # octane [111-65-9] -- eps(298 K) = 1.941
    'CCCCCCCC': (
        (2.259, -0.00084212, -7.5758e-07, 0.0),
        (233.0, 393.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # heptane [142-82-5] -- eps(298 K) = 1.911
    'CCCCCCC': (
        (2.474, -0.0022577, 1.2428e-06, 0.0),
        (273.0, 373.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # hexane [110-54-3] -- eps(298 K) = 1.882
    'CCCCCC': (
        (1.9768, 0.00070933, -3.447e-06, 0.0),
        (293.0, 473.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # pentane [109-66-0] -- eps(298 K) = 1.837
    'CCCCC': (
        (1.8371, 0.0, 0.0, 0.0),
        (293.2, 293.2),
        'single point',
        'CRC Handbook single measured value at 293.2 K (via chemicals 1.5.2), held constant',
    ),
    # carbon dioxide [124-38-9] -- eps(298 K) = 1.428
    'O=C=O': (
        (0.79062, 0.010639, -2.851e-05, 0.0),
        (220.0, 300.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # ethylene [74-85-1] -- eps(298 K) = 1.321
    'C=C': (
        (1.3546, 0.0062614, -2.1374e-05, 0.0),
        (200.0, 270.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # methane [74-82-8] -- eps(298 K) = 0.454
    'C': (
        (1.5996, 0.0027434, -2.2086e-05, 0.0),
        (91.0, 184.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # oxygen [7782-44-7] -- eps(298 K) = 0.027
    'O=O': (
        (1.5434, 0.0014615, -2.1964e-05, 0.0),
        (55.0, 154.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # hydrogen [1333-74-0] -- eps(298 K) = -0.216
    '[H][H]': (
        (1.3327, -0.0051946, 0.0, 0.0),
        (14.0, 19.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
    # nitrogen [7727-37-9] -- eps(298 K) = -1.760
    'N#N': (
        (1.255, 0.0067949, -5.6704e-05, 0.0),
        (63.0, 126.0),
        'polynomial',
        'CRC Handbook permittivity correlation (via chemicals 1.5.2)',
    ),
}

# angstrom. chemicals.elements.periodic_table (Alvarez 2013 / Bondi).
VDW_RADII: dict[str, float] = {
    'H': 1.1,
    'C': 1.7,
    'N': 1.55,
    'O': 1.52,
    'F': 1.47,
    'Na': 2.27,
    'Mg': 1.73,
    'P': 1.8,
    'S': 1.8,
    'Cl': 1.75,
    'K': 2.75,
    'Ca': 2.31,
    'Br': 1.83,
    'I': 1.98,
    'Li': 1.81,
}
