"""Layer 1 -- ELEMENTS: the floor every chain stands on.

GENERATED by ``tools/build_element_data.py`` from ``chemicals`` 1.5.2 and
``thermo`` 0.6.1. Do not hand-edit: regenerate. That script's docstring carries
the full argument; the short version is below.

**For an element in its standard state the data is FREE AND EXACT.** Hf = Gf = 0
by definition, with no source to cite and no cross-check that could exist. That
makes an estimator returning a non-zero formation energy for a reference state a
DETECTABLE ERROR rather than a judgement call, and three have now been detected
in this repo:

    Cl2  Joback: Hf = -74.81 kJ/mol     (~1e13 in any K)  -- fixed 2026-08-16
    F2   Joback: Gf = -440.5  kJ/mol                      -- fixed here
    S8   Joback: Gf = +275.96 kJ/mol    (~e^91 in any K)  -- fixed here

The first was fixed species by species, which is why the lesson did not
generalise. ``thermochemistry`` now REFUSES to let any estimator price an
elemental species at all: it comes from this table or it is refused by name.
That closes the class rather than one member of it.

## THE STANDARD STATE IS NOT ALWAYS THE OBVIOUS ONE

A ``ThermoData`` in this project is on the IDEAL-GAS basis. So a reference state
that is a GAS has an ideal-gas record of exactly zero, and a reference state
that is CONDENSED does not -- its ideal-gas record is the vaporisation or
sublimation energy, which is a real measured number:

    H2 N2 O2 F2 Cl2   gaseous reference state    Hf = Gf = 0   exact, free
    Br2               LIQUID  reference state    Hf = +30.90  Gf = +3.08
    I2                SOLID   reference state    Hf = +62.40  Gf = +19.29
    S8 (rhombic)      SOLID   reference state    Hf = +100.42 Gf = +48.68

**Br2 and I2 were pinned to 0.0 in this repo before this module existed.** The
species-by-species fix for the Cl2 bug put a 62 kJ/mol error into iodine while
taking a 75 kJ/mol error out of chlorine -- the same bug one level up, and the
reason the class fix had to replace it rather than extend it.

The independent cross-check on a condensed reference state is that shifting the
ideal-gas value back down into its own phase must return zero:

    Gf(g) + R T ln(Psat/P_std) - Hfus*(1 - T/Tm)  ==  0

and nothing in that expression touched the formation table -- Psat comes from
Tb/Tc/Pc through Lee-Kesler and Hfus/Tm are separate measurements. It is
measured in ``tests/test_element_data.py`` and reported in
``validation/game_gates.py``.

## WHAT IS NOT HERE, AND WHY IT IS REFUSED RATHER THAN ESTIMATED

  * **graphite and every metal.** The reference state is a metallic or covalent
    LATTICE, and this engine's species are molecules. The ideal-gas record for
    ``[C]`` is the carbon ATOM at Gf +671 kJ/mol -- a real number that is not
    charcoal.
  * **a bare monatomic symbol** (``[S]``, ``[C]``, ``[Fe]``). The most ambiguous
    way there is to name an allotrope; answering with the gas atom's value is a
    confident answer to a different question. The refusal names the
    reference-state SMILES to charge instead.
"""

from __future__ import annotations

from typing import NamedTuple


class ElementalRecord(NamedTuple):
    """One elemental species, on the IDEAL-GAS basis, with provenance."""

    name: str
    cas: str
    element: str
    n_atoms: int
    reference_state: bool          # is this SMILES the element's standard state
    reference_phase: str | None    # "g" / "l" / "s" -- which phase is zero
    Hf: float                      # kJ/mol, ideal gas, 298.15 K
    Gf: float                      # kJ/mol, ideal gas, 298.15 K
    Cp_coeffs: tuple               # J/(mol K), a + bT + cT^2 + dT^3
    Tb: float | None
    Tc: float | None
    Pc: float | None
    Vc: float | None
    Hvap: float | None
    Tm: float | None
    Hfus: float | None
    formation_source: str
    physical_source: str
    cp_source: str


class ReferenceState(NamedTuple):
    """Which species and phase is an element's zero, and its absolute entropy."""

    species: str                   # human name, e.g. "S(rhombic)"
    smiles: str | None             # None where the reference state is a lattice
    phase: str                     # "g" / "l" / "s"
    S0: float                      # J/(mol K), per mole of the TABULATED species
    atoms_per_unit: int            # atoms of the element in that formula unit
    source: str



# ---------------------------------------------------------------------------
# The element reference states: the basis every derivation here stands on
# ---------------------------------------------------------------------------
# ``atoms_per_unit`` is load-bearing and easy to get wrong:
# ``chemicals`` tabulates sulfur under formula "S", so its S0 of 32.1 is PER
# GRAM-ATOM, while bromine is tabulated as "Br2" and its 152.2 is per mole of
# Br2. Divide by the wrong one and every sulfur compound's entropy of
# formation is out by a factor of eight.
REFERENCE_STATES: dict[str, ReferenceState] = {
    'H': ReferenceState(
        species='H2(g)', smiles='[H][H]', phase='g',
        S0=130.7, atoms_per_unit=2,
        source='CRC via chemicals 1.5.2',
    ),
    'N': ReferenceState(
        species='N2(g)', smiles='N#N', phase='g',
        S0=191.6, atoms_per_unit=2,
        source='CRC via chemicals 1.5.2',
    ),
    'O': ReferenceState(
        species='O2(g)', smiles='O=O', phase='g',
        S0=205.2, atoms_per_unit=2,
        source='CRC via chemicals 1.5.2',
    ),
    'F': ReferenceState(
        species='F2(g)', smiles='FF', phase='g',
        S0=202.8, atoms_per_unit=2,
        source='CRC via chemicals 1.5.2',
    ),
    'Cl': ReferenceState(
        species='Cl2(g)', smiles='ClCl', phase='g',
        S0=223.1, atoms_per_unit=2,
        source='CRC via chemicals 1.5.2',
    ),
    'Br': ReferenceState(
        species='Br2(l)', smiles='BrBr', phase='l',
        S0=152.2, atoms_per_unit=2,
        source='CRC via chemicals 1.5.2',
    ),
    'I': ReferenceState(
        species='I2(s)', smiles='II', phase='s',
        S0=116.1, atoms_per_unit=2,
        source='CRC via chemicals 1.5.2',
    ),
    'S': ReferenceState(
        species='S(rhombic)', smiles='S1SSSSSSS1', phase='s',
        S0=32.1, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'C': ReferenceState(
        species='C(graphite)', smiles=None, phase='s',
        S0=5.7, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'P': ReferenceState(
        species='P(white)', smiles=None, phase='s',
        S0=41.1, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Na': ReferenceState(
        species='Na(s)', smiles=None, phase='s',
        S0=51.3, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'K': ReferenceState(
        species='K(s)', smiles=None, phase='s',
        S0=64.7, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Ca': ReferenceState(
        species='Ca(s)', smiles=None, phase='s',
        S0=41.6, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Fe': ReferenceState(
        species='Fe(s)', smiles=None, phase='s',
        S0=27.3, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Cu': ReferenceState(
        species='Cu(s)', smiles=None, phase='s',
        S0=33.2, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Zn': ReferenceState(
        species='Zn(s)', smiles=None, phase='s',
        S0=41.6, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Hg': ReferenceState(
        species='Hg(l)', smiles=None, phase='l',
        S0=75.9, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Mg': ReferenceState(
        species='Mg(s)', smiles=None, phase='s',
        S0=32.7, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Al': ReferenceState(
        species='Al(s)', smiles=None, phase='s',
        S0=28.3, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Mn': ReferenceState(
        species='Mn(s)', smiles=None, phase='s',
        S0=32.0, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Ag': ReferenceState(
        species='Ag(s)', smiles=None, phase='s',
        S0=42.6, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Ba': ReferenceState(
        species='Ba(s)', smiles=None, phase='s',
        S0=62.5, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Pb': ReferenceState(
        species='Pb(s)', smiles=None, phase='s',
        S0=64.8, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Li': ReferenceState(
        species='Li(s)', smiles=None, phase='s',
        S0=29.1, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Rb': ReferenceState(
        species='Rb(s)', smiles=None, phase='s',
        S0=76.8, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Cs': ReferenceState(
        species='Cs(s)', smiles=None, phase='s',
        S0=85.2, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Sr': ReferenceState(
        species='Sr(s)', smiles=None, phase='s',
        S0=55.0, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Cr': ReferenceState(
        species='Cr(s)', smiles=None, phase='s',
        S0=23.8, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Co': ReferenceState(
        species='Co(s)', smiles=None, phase='s',
        S0=30.0, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Ni': ReferenceState(
        species='Ni(s)', smiles=None, phase='s',
        S0=29.9, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Cd': ReferenceState(
        species='Cd(s)', smiles=None, phase='s',
        S0=51.8, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
    'Tl': ReferenceState(
        species='Tl(s)', smiles=None, phase='s',
        S0=64.2, atoms_per_unit=1,
        source='CRC via chemicals 1.5.2',
    ),
}


# ---------------------------------------------------------------------------
# The elemental species, on the IDEAL-GAS basis
# ---------------------------------------------------------------------------
ELEMENTAL: dict[str, ElementalRecord] = {
    # hydrogen  (CAS 1333-74-0; EXACT by definition)
    '[H][H]': ElementalRecord(
        name='hydrogen', cas='1333-74-0', element='H', n_atoms=2,
        reference_state=True, reference_phase='g',
        Hf=0.0, Gf=0.0,
        Cp_coeffs=(27.14, 0.009274, -1.381e-05, 7.645e-09),
        Tb=20.37, Tc=33.19, Pc=13.13, Vc=64.1,
        Hvap=0.9, Tm=13.81, Hfus=0.117,
        formation_source='element reference state (gaseous): Hf = Gf = 0 BY DEFINITION',
        physical_source='curated measured (Poling/CRC), carried forward verbatim from the pre-existing entry',
        cp_source='carried forward verbatim (Poling appendix A)',
    ),
    # nitrogen  (CAS 7727-37-9; EXACT by definition)
    'N#N': ElementalRecord(
        name='nitrogen', cas='7727-37-9', element='N', n_atoms=2,
        reference_state=True, reference_phase='g',
        Hf=0.0, Gf=0.0,
        Cp_coeffs=(31.15, -0.01357, 2.68e-05, -1.168e-08),
        Tb=77.35, Tc=126.2, Pc=33.98, Vc=90.1,
        Hvap=5.58, Tm=63.15, Hfus=0.71,
        formation_source='element reference state (gaseous): Hf = Gf = 0 BY DEFINITION',
        physical_source='curated measured (Poling/CRC), carried forward verbatim from the pre-existing entry',
        cp_source='carried forward verbatim (Poling appendix A)',
    ),
    # oxygen  (CAS 7782-44-7; EXACT by definition)
    'O=O': ElementalRecord(
        name='oxygen', cas='7782-44-7', element='O', n_atoms=2,
        reference_state=True, reference_phase='g',
        Hf=0.0, Gf=0.0,
        Cp_coeffs=(28.11, -3.68e-06, 1.746e-05, -1.065e-08),
        Tb=90.19, Tc=154.58, Pc=50.43, Vc=73.4,
        Hvap=6.82, Tm=54.36, Hfus=0.444,
        formation_source='element reference state (gaseous): Hf = Gf = 0 BY DEFINITION',
        physical_source='curated measured (Poling/CRC), carried forward verbatim from the pre-existing entry',
        cp_source='carried forward verbatim (Poling appendix A)',
    ),
    # fluorine  (CAS 7782-41-4; EXACT by definition)
    'FF': ElementalRecord(
        name='fluorine', cas='7782-41-4', element='F', n_atoms=2,
        reference_state=True, reference_phase='g',
        Hf=0.0, Gf=0.0,
        Cp_coeffs=(24.620490740116, 0.025621720303, -8.438317e-06, -8.251e-09),
        Tb=85.04, Tc=144.3, Pc=52.152, Vc=66.2,
        Hvap=6.903, Tm=53.48, Hfus=0.51,
        formation_source='element reference state (gaseous): Hf = Gf = 0 BY DEFINITION',
        physical_source='Tb=CRC_INORG; Tm=CRC_INORG; Hfus=CRC; Tc=MATTHEWS; Pc=MATTHEWS; Vc=MATTHEWS; Hvap from Lee-Kesler by Clausius-Clapeyron',
        cp_source='TRCIG, sampled 273-600 K and fitted (worst residual 0.08%)',
    ),
    # chlorine  (CAS 7782-50-5; EXACT by definition)
    'ClCl': ElementalRecord(
        name='chlorine', cas='7782-50-5', element='Cl', n_atoms=2,
        reference_state=True, reference_phase='g',
        Hf=0.0, Gf=0.0,
        Cp_coeffs=(28.54, 0.0238, -2.14e-05, 6.31e-09),
        Tb=239.11, Tc=417.15, Pc=77.11, Vc=123.8,
        Hvap=20.41, Tm=171.65, Hfus=6.41,
        formation_source='element reference state (gaseous): Hf = Gf = 0 BY DEFINITION',
        physical_source='curated measured (Poling/CRC), carried forward verbatim from the pre-existing entry',
        cp_source='carried forward verbatim (Poling appendix A)',
    ),
    # bromine  (CAS 7726-95-6; reference state, condensed -- the gas record is real data)
    'BrBr': ElementalRecord(
        name='bromine', cas='7726-95-6', element='Br', n_atoms=2,
        reference_state=True, reference_phase='l',
        Hf=30.9, Gf=3.083,
        Cp_coeffs=(33.86, 0.0113, -1.19e-05, 4.13e-09),
        Tb=331.9, Tc=584.15, Pc=103.4, Vc=127.0,
        Hvap=29.96, Tm=265.9, Hfus=10.57,
        formation_source='Hf and S0 both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='curated measured (Poling/CRC), carried forward verbatim from the pre-existing entry',
        cp_source='carried forward verbatim (Poling appendix A)',
    ),
    # iodine  (CAS 7553-56-2; reference state, condensed -- the gas record is real data)
    'II': ElementalRecord(
        name='iodine', cas='7553-56-2', element='I', n_atoms=2,
        reference_state=True, reference_phase='s',
        Hf=62.4, Gf=19.288,
        Cp_coeffs=(35.6, 0.009, -1e-05, 3.5e-09),
        Tb=457.5, Tc=819.0, Pc=117.5, Vc=155.0,
        Hvap=41.57, Tm=386.85, Hfus=15.52,
        formation_source='Hf and S0 both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='curated measured (Poling/CRC), carried forward verbatim from the pre-existing entry',
        cp_source='carried forward verbatim (Poling appendix A)',
    ),
    # sulfur  (CAS 10544-50-0; reference state, condensed -- the gas record is real data)
    'S1SSSSSSS1': ElementalRecord(
        name='sulfur', cas='10544-50-0', element='S', n_atoms=8,
        reference_state=True, reference_phase='s',
        Hf=100.416, Gf=48.684,
        Cp_coeffs=(63.007691752014, 0.527244285388, -0.000876130445, 5.15935e-07),
        Tb=717.76, Tc=1314.0, Pc=117.537, Vc=454.55,
        Hvap=64.304, Tm=388.36, Hfus=13.768,
        formation_source='Hf and S0 both from JANAF via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tb=CRC_INORG; Tm=CRC_INORG; Hfus=CRC; Tc=MATTHEWS; Pc=MATTHEWS; Vc=WEBBOOK; Hvap from Lee-Kesler by Clausius-Clapeyron [molar values from CAS 7704-34-9, tabulated per gram-atom, multiplied by 8]',
        cp_source='JANAF, sampled 273-600 K and fitted (worst residual 0.13%)',
    ),
    # ozone  (CAS 10028-15-6; elemental, NOT a reference state)
    'O=[O+][O-]': ElementalRecord(
        name='ozone', cas='10028-15-6', element='O', n_atoms=3,
        reference_state=False, reference_phase='g',
        Hf=142.7, Gf=163.243,
        Cp_coeffs=(19.587717988626, 0.083013418283, -6.0890723e-05, 1.1047e-08),
        Tb=161.8, Tc=261.0, Pc=55.729, Vc=89.0,
        Hvap=14.836, Tm=80.15, Hfus=None,
        formation_source='Hf and S0 both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tb=CRC_INORG; Tm=CRC_INORG; Tc=MATTHEWS; Pc=MATTHEWS; Vc=MATTHEWS; Hvap from Lee-Kesler by Clausius-Clapeyron',
        cp_source='JANAF, sampled 273-600 K and fitted (worst residual 0.11%)',
    ),
}


# ---------------------------------------------------------------------------
# Elements whose reference state this engine cannot hold as a molecule
# ---------------------------------------------------------------------------
# Kept as data rather than dropped, so the REFUSAL can name the reason. A
# refusal that says "no data" where the truth is "your representation cannot
# express this" is a worse answer than no answer.
LATTICE_ELEMENTS: dict[str, str] = {'C': 'graphite -- a covalent lattice', 'P': 'white phosphorus -- a molecular solid whose P4 SMILES RDKit canonicalises to aromatic phosphorus', 'Na': 'a metallic lattice', 'K': 'a metallic lattice', 'Ca': 'a metallic lattice', 'Fe': 'a metallic lattice', 'Cu': 'a metallic lattice', 'Zn': 'a metallic lattice', 'Hg': 'liquid mercury -- a metal, not a molecule'}


def element_of(molecule) -> str | None:
    """The element symbol if ``molecule`` is a single-element NEUTRAL species.

    NET charge, not the presence of formal charges: nitrobenzene is written
    ``O=[N+]([O-])c1ccccc1`` and is an ordinary neutral molecule that the
    estimators must keep pricing, while ``[Cl-].[Cl-]`` has net charge -2 and is
    two chloride ions that Joback was happily pricing as one neutral species at
    -74.74 kJ/mol -- the Cl2 value, for a pair of ions.

    Returns None for anything with more than one element, so methane (``C`` ->
    C1H4) is not mistaken for elemental carbon.
    """
    if molecule.charge != 0:
        return None
    counts = molecule.element_counts()
    if len(counts) != 1:
        return None
    return next(iter(counts))


def is_monatomic(molecule) -> bool:
    """Whether a species is a bare single atom of one element.

    Separated from ``element_of`` because the two get DIFFERENT refusals: a
    monatomic symbol is an ambiguous way to name an allotrope, whereas a
    polyatomic elemental species missing from the table is simply uncurated.
    """
    counts = molecule.element_counts()
    return len(counts) == 1 and next(iter(counts.values())) == 1
