"""Layer 1 -- AQUEOUS IONS on the conventional ``Gf(H+,aq) = 0`` basis.

GENERATED by ``tools/build_ion_data.py`` from the CRC aqueous-ion table shipped
with ``chemicals`` 1.5.2. Do not hand-edit: regenerate. That script's docstring
carries the argument; the short version is below.

## THE ONE THING TO KNOW BEFORE USING THIS MODULE

**THIS IS A DIFFERENT ZERO FROM ``electrolyte``'S IONS AND THE TWO MUST NEVER BE
SUBTRACTED FROM EACH OTHER.** ``electrolyte`` back-calculates each ion from a
measured pKa against *this project's* water, with ``Gf(H3O+) = Gf(H2O, liquid)``.
That reproduces acidity exactly and is the right basis for a proton transfer.
This module is the conventional aqueous formation scale, anchored on
``Gf(H+,aq) = 0``, which is the right basis for a LATTICE subtraction. Chloride
reads -111.73 kJ/mol there and -131.20 here.

Neither number is wrong. Mixing them costs 3.4 decades of Ksp. There is no
import between the two modules and there should not be one -- the same
separation ``mineral_data`` keeps from the phase model.

**So: this module is REFERENCE DATA, not a ``ThermochemistryProvider`` tier.**
Nothing in the engine's RHS reads it. ``properties/solubility_product.py`` is its
only consumer, and it consumes ``mineral_data`` on the other side of the same
subtraction -- both derived against the element reference states in
``element_data``.

## WHERE IT CAME FROM, AND THE MEASUREMENT THAT WAS WRONG ABOUT IT

M3 was recorded as blocked on hand-curation because ``chemicals`` "has no
aqueous ion values and hands back the GAS-PHASE ion" -- measured, ``Hfs``/
``S0s``/``Hfl`` are ``None`` for Na+ and ``Hfg`` is +609343 J/mol.

**That was true of the FUNCTIONS and false of the PACKAGE.** ``chemicals`` 1.5.2
ships ``Electrolytes/CRC Thermodynamic Properties of Aqueous Ions.tsv`` -- 173
ions, one compilation, with the H+ row carrying 0/0/0/0, which is the
conventional scale stated by the table rather than assumed. No accessor function
reads it. **A refusal from an API is not evidence that the data is absent**, the
mirror image of this project's older rule that a successful call can be a wrong
answer.

## THE CROSS-CHECK EVERY ENTRY PASSED, AND WHY IT PROVES THE BASIS

``Gf`` is re-derived from the SAME row's ``Hf`` and ``S(aq)`` against the element
reference entropies in ``element_data``:

    dS_f = S(ion,aq) + (z/2) S0(H2,g) - sum_el nu_el S0(el, reference state)

The ``(z/2) S0(H2)`` term exists only because the convention settles the electron
against half a hydrogen molecule and sets ``S(H+,aq) = 0``. Drop it and sodium
misses by 19.48 kJ/mol -- exactly T S0(H2)/2 at 298.15 K. Keep it and every accepted entry closes to within a few
hundred J/mol -- the rounding floor of a table quoted to 100 J/mol and 0.1
J/(mol K). ``crosscheck`` on each record is that residual, kept as data.

An entry that fails by more than 1 kJ/mol is REFUSED rather than written, and so
is one whose hand-written SMILES does not have the element counts and formal
charge of the CRC formula string it claims to be.
"""

from __future__ import annotations

from typing import NamedTuple


class AqueousIon(NamedTuple):
    """One ion in water, on the conventional ``Gf(H+,aq) = 0`` scale.

    ``Hf``/``Gf`` are NOT on the ideal-gas basis a ``ThermoData`` carries and NOT
    on ``electrolyte``'s pKa basis, which is exactly why this is a separate type
    in a separate module: either confusion is a silent wrong answer worth decades
    of Ksp.
    """

    smiles: str                    # canonical, as the engine names the ion
    formula: str                   # the CRC table's own formula string
    cas: str
    name: str
    charge: int
    elements: dict                 # element counts of the ion
    Hf: float                      # kJ/mol, aqueous, infinite dilution, 298.15 K
    Gf: float                      # kJ/mol, aqueous, infinite dilution, 298.15 K
    S0: float                      # J/(mol K), CONVENTIONAL (S(H+,aq) = 0)
    Cp: float | None               # J/(mol K), where tabulated
    purpose: str                   # what a chain wants it for
    crosscheck: float              # kJ/mol, Gf(tabulated) - Gf(derived from Hf,S)
    source: str



AQUEOUS_IONS: dict[str, AqueousIon] = {
    # the zero of the whole scale -- 0/0/0 in the table itself
    '[H+]': AqueousIon(
        smiles='[H+]', formula='H+',
        cas='12408-02-5', name='Hydrogen ion',
        charge=1, elements={'H': 1},
        Hf=0.0, Gf=0.0, S0=0.0, Cp=0.0,
        purpose='the zero of the whole scale -- 0/0/0 in the table itself',
        crosscheck=0.0,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # lithium
    '[Li+]': AqueousIon(
        smiles='[Li+]', formula='Li+',
        cas='17341-24-1', name='Lithium ion',
        charge=1, elements={'Li': 1},
        Hf=-278.5, Gf=-293.3, S0=13.4, Cp=68.6,
        purpose='lithium',
        crosscheck=0.0031,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # rock salt, soda ash, Glauber's salt, caustic soda
    '[Na+]': AqueousIon(
        smiles='[Na+]', formula='Na+',
        cas='17341-25-2', name='Sodium ion',
        charge=1, elements={'Na': 1},
        Hf=-240.1, Gf=-261.9, S0=59.0, Cp=46.4,
        purpose="rock salt, soda ash, Glauber's salt, caustic soda",
        crosscheck=-0.0201,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # saltpetre, potash, caustic potash, bisulfate
    '[K+]': AqueousIon(
        smiles='[K+]', formula='K+',
        cas='24203-36-9', name='Potassium ion',
        charge=1, elements={'K': 1},
        Hf=-252.4, Gf=-283.3, S0=102.5, Cp=21.8,
        purpose='saltpetre, potash, caustic potash, bisulfate',
        crosscheck=-0.1458,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # rubidium
    '[Rb+]': AqueousIon(
        smiles='[Rb+]', formula='Rb+',
        cas='22537-38-8', name='Rubidium ion',
        charge=1, elements={'Rb': 1},
        Hf=-251.2, Gf=-284.0, S0=121.5, Cp=None,
        purpose='rubidium',
        crosscheck=0.0114,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # caesium
    '[Cs+]': AqueousIon(
        smiles='[Cs+]', formula='Cs+',
        cas='18459-37-5', name='Cesium ion',
        charge=1, elements={'Cs': 1},
        Hf=-258.3, Gf=-292.0, S0=133.1, Cp=-10.5,
        purpose='caesium',
        crosscheck=0.0655,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # magnesia, and hard water
    '[Mg+2]': AqueousIon(
        smiles='[Mg+2]', formula='Mg+2',
        cas='22537-22-0', name='Magnesium ion',
        charge=2, elements={'Mg': 1},
        Hf=-466.9, Gf=-454.8, S0=-138.1, Cp=None,
        purpose='magnesia, and hard water',
        crosscheck=0.1442,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # calcite, lime, GYPSUM -- M1's three acid-displacement steps
    '[Ca+2]': AqueousIon(
        smiles='[Ca+2]', formula='Ca+2',
        cas='14127-61-8', name='Calcium ion',
        charge=2, elements={'Ca': 1},
        Hf=-542.8, Gf=-553.6, S0=-53.1, Cp=None,
        purpose="calcite, lime, GYPSUM -- M1's three acid-displacement steps",
        crosscheck=-0.0666,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # strontium
    '[Sr+2]': AqueousIon(
        smiles='[Sr+2]', formula='Sr+2',
        cas='22537-39-9', name='Strontium ion',
        charge=2, elements={'Sr': 1},
        Hf=-545.8, Gf=-559.5, S0=-32.6, Cp=None,
        purpose='strontium',
        crosscheck=-0.8497,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # barium -- BaSO4 is the textbook metathesis precipitate
    '[Ba+2]': AqueousIon(
        smiles='[Ba+2]', formula='Ba+2',
        cas='22541-12-4', name='Barium ion',
        charge=2, elements={'Ba': 1},
        Hf=-537.6, Gf=-560.8, S0=9.6, Cp=None,
        purpose='barium -- BaSO4 is the textbook metathesis precipitate',
        crosscheck=-0.0039,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # manganese(II)
    '[Mn+2]': AqueousIon(
        smiles='[Mn+2]', formula='Mn+2',
        cas='16397-91-4', name='Manganese ion',
        charge=2, elements={'Mn': 1},
        Hf=-220.8, Gf=-228.1, S0=-73.6, Cp=50.0,
        purpose='manganese(II)',
        crosscheck=0.1836,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # green vitriol, chain 2's seed
    '[Fe+2]': AqueousIon(
        smiles='[Fe+2]', formula='Fe+2',
        cas='15438-31-0', name='Iron (ferrous) ion',
        charge=2, elements={'Fe': 1},
        Hf=-89.1, Gf=-78.9, S0=-137.7, Cp=None,
        purpose="green vitriol, chain 2's seed",
        crosscheck=-0.0265,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # ferric iron
    '[Fe+3]': AqueousIon(
        smiles='[Fe+3]', formula='Fe+3',
        cas='20074-52-6', name='Iron (ferric) ion',
        charge=3, elements={'Fe': 1},
        Hf=-48.5, Gf=-4.7, S0=-315.9, Cp=None,
        purpose='ferric iron',
        crosscheck=-0.0728,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # cobalt(II)
    '[Co+2]': AqueousIon(
        smiles='[Co+2]', formula='Co+2',
        cas='22541-53-3', name='Cobalt (cobaltous) ion',
        charge=2, elements={'Co': 1},
        Hf=-58.2, Gf=-54.4, S0=-113.0, Cp=None,
        purpose='cobalt(II)',
        crosscheck=0.1328,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # nickel(II)
    '[Ni+2]': AqueousIon(
        smiles='[Ni+2]', formula='Ni+2',
        cas='14701-22-5', name='Nickel ion',
        charge=2, elements={'Ni': 1},
        Hf=-54.0, Gf=-45.6, S0=-128.9, Cp=None,
        purpose='nickel(II)',
        crosscheck=0.022,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # copper(I)
    '[Cu+]': AqueousIon(
        smiles='[Cu+]', formula='Cu+',
        cas='17493-86-6', name='Copper (cuprous) ion',
        charge=1, elements={'Cu': 1},
        Hf=71.7, Gf=50.0, S0=40.6, Cp=None,
        purpose='copper(I)',
        crosscheck=-0.0096,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # blue vitriol
    '[Cu+2]': AqueousIon(
        smiles='[Cu+2]', formula='Cu+2',
        cas='15158-11-9', name='Copper (cupric) ion',
        charge=2, elements={'Cu': 1},
        Hf=64.8, Gf=65.5, S0=-99.6, Cp=None,
        purpose='blue vitriol',
        crosscheck=0.0739,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # zinc
    '[Zn+2]': AqueousIon(
        smiles='[Zn+2]', formula='Zn+2',
        cas='23713-49-7', name='Zinc ion',
        charge=2, elements={'Zn': 1},
        Hf=-153.9, Gf=-147.1, S0=-112.1, Cp=46.0,
        purpose='zinc',
        crosscheck=-0.0575,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # cadmium
    '[Cd+2]': AqueousIon(
        smiles='[Cd+2]', formula='Cd+2',
        cas='22537-48-0', name='Cadmium ion',
        charge=2, elements={'Cd': 1},
        Hf=-75.9, Gf=-77.6, S0=-73.2, Cp=None,
        purpose='cadmium',
        crosscheck=-0.0005,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # silver -- AgCl is 'add A to B and it goes cloudy'
    '[Ag+]': AqueousIon(
        smiles='[Ag+]', formula='Ag+',
        cas='14701-21-4', name='Silver ion',
        charge=1, elements={'Ag': 1},
        Hf=105.6, Gf=77.1, S0=72.7, Cp=21.8,
        purpose="silver -- AgCl is 'add A to B and it goes cloudy'",
        crosscheck=-0.0416,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # mercury(II)
    '[Hg+2]': AqueousIon(
        smiles='[Hg+2]', formula='Hg+2',
        cas='14302-87-5', name='Mercury(II) (mercuric) ion',
        charge=2, elements={'Hg': 1},
        Hf=171.1, Gf=164.4, S0=-32.2, Cp=None,
        purpose='mercury(II)',
        crosscheck=0.0382,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # lead -- chrome yellow, and the golden rain of PbI2
    '[Pb+2]': AqueousIon(
        smiles='[Pb+2]', formula='Pb+2',
        cas='14280-50-3', name='Lead ion',
        charge=2, elements={'Pb': 1},
        Hf=-1.7, Gf=-24.4, S0=10.5, Cp=None,
        purpose='lead -- chrome yellow, and the golden rain of PbI2',
        crosscheck=0.0787,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # aluminium
    '[Al+3]': AqueousIon(
        smiles='[Al+3]', formula='Al+3',
        cas='22537-23-1', name='Aluminum ion',
        charge=3, elements={'Al': 1},
        Hf=-531.0, Gf=-485.0, S0=-321.7, Cp=None,
        purpose='aluminium',
        crosscheck=0.0998,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # thallium(I)
    '[Tl+]': AqueousIon(
        smiles='[Tl+]', formula='Tl+',
        cas='22537-56-0', name='Thallium ion',
        charge=1, elements={'Tl': 1},
        Hf=5.4, Gf=-32.4, S0=125.5, Cp=None,
        purpose='thallium(I)',
        crosscheck=-0.0393,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # ammonium -- the one polyatomic cation a bench sees daily
    '[NH4+]': AqueousIon(
        smiles='[NH4+]', formula='NH4+',
        cas='14798-03-9', name='Ammonium ion',
        charge=1, elements={'N': 1, 'H': 4},
        Hf=-132.5, Gf=-79.3, S0=113.4, Cp=79.9,
        purpose='ammonium -- the one polyatomic cation a bench sees daily',
        crosscheck=-0.0049,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # hydroxide
    '[OH-]': AqueousIon(
        smiles='[OH-]', formula='OH-',
        cas='14280-30-9', name='Hydroxyl ion',
        charge=-1, elements={'O': 1, 'H': 1},
        Hf=-230.0, Gf=-157.2, S0=-10.8, Cp=-148.5,
        purpose='hydroxide',
        crosscheck=0.0216,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # fluoride
    '[F-]': AqueousIon(
        smiles='[F-]', formula='F-',
        cas='16984-48-8', name='Fluoride ion',
        charge=-1, elements={'F': 1},
        Hf=-332.6, Gf=-278.8, S0=-13.8, Cp=-106.7,
        purpose='fluoride',
        crosscheck=-0.031,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # chloride
    '[Cl-]': AqueousIon(
        smiles='[Cl-]', formula='Cl-',
        cas='16887-00-6', name='Chloride ion',
        charge=-1, elements={'Cl': 1},
        Hf=-167.2, Gf=-131.2, S0=56.5, Cp=-136.4,
        purpose='chloride',
        crosscheck=0.1027,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # bromide
    '[Br-]': AqueousIon(
        smiles='[Br-]', formula='Br-',
        cas='24959-67-9', name='Bromide ion',
        charge=-1, elements={'Br': 1},
        Hf=-121.6, Gf=-104.0, S0=82.4, Cp=-141.8,
        purpose='bromide',
        crosscheck=-0.0058,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # iodide
    '[I-]': AqueousIon(
        smiles='[I-]', formula='I-',
        cas='20461-54-5', name='Iodide ion',
        charge=-1, elements={'I': 1},
        Hf=-55.2, Gf=-51.6, S0=111.3, Cp=-142.3,
        purpose='iodide',
        crosscheck=-0.0076,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # sulfide
    '[S-2]': AqueousIon(
        smiles='[S-2]', formula='S-2',
        cas='18496-25-8', name='Sulfide ion',
        charge=-2, elements={'S': 1},
        Hf=33.1, Gf=85.8, S0=-14.6, Cp=None,
        purpose='sulfide',
        crosscheck=-0.1918,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # hydrosulfide -- what H2S actually gives in water
    '[SH-]': AqueousIon(
        smiles='[SH-]', formula='SH-',
        cas='15035-72-0', name='Hydrosulfide ion',
        charge=-1, elements={'S': 1, 'H': 1},
        Hf=-17.6, Gf=12.1, S0=62.8, Cp=None,
        purpose='hydrosulfide -- what H2S actually gives in water',
        crosscheck=-0.115,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # disulfide -- pyrite's anion
    '[S-][S-]': AqueousIon(
        smiles='[S-][S-]', formula='S2-2',
        cas='16734-12-6', name='Disulfide ion',
        charge=-2, elements={'S': 2},
        Hf=30.1, Gf=79.5, S0=28.5, Cp=None,
        purpose="disulfide -- pyrite's anion",
        crosscheck=-0.2122,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # cyanide
    '[C-]#N': AqueousIon(
        smiles='[C-]#N', formula='CN-',
        cas='57-12-5', name='Cyanide ion',
        charge=-1, elements={'C': 1, 'N': 1},
        Hf=150.6, Gf=172.4, S0=94.1, Cp=None,
        purpose='cyanide',
        crosscheck=0.1096,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # thiocyanate
    'N#C[S-]': AqueousIon(
        smiles='N#C[S-]', formula='SCN-',
        cas='302-04-5', name='Thiocyanate ion',
        charge=-1, elements={'S': 1, 'C': 1, 'N': 1},
        Hf=76.4, Gf=92.7, S0=144.3, Cp=-40.2,
        purpose='thiocyanate',
        crosscheck=0.0061,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # nitrate -- saltpetre, and chain 2
    'O=[N+]([O-])[O-]': AqueousIon(
        smiles='O=[N+]([O-])[O-]', formula='NO3-',
        cas='14797-55-8', name='Nitrate ion',
        charge=-1, elements={'N': 1, 'O': 3},
        Hf=-207.4, Gf=-111.3, S0=146.4, Cp=-86.6,
        purpose='nitrate -- saltpetre, and chain 2',
        crosscheck=-0.0683,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # nitrite
    'O=N[O-]': AqueousIon(
        smiles='O=N[O-]', formula='NO2-',
        cas='14797-65-0', name='Nitrite ion',
        charge=-1, elements={'N': 1, 'O': 2},
        Hf=-104.6, Gf=-32.2, S0=123.0, Cp=-97.5,
        purpose='nitrite',
        crosscheck=-0.1548,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # sulfate -- the vitriols and Glauber's salt
    'O=S(=O)([O-])[O-]': AqueousIon(
        smiles='O=S(=O)([O-])[O-]', formula='SO4-2',
        cas='14808-79-8', name='Sulfate ion',
        charge=-2, elements={'S': 1, 'O': 4},
        Hf=-909.3, Gf=-744.5, S0=20.1, Cp=-293.0,
        purpose="sulfate -- the vitriols and Glauber's salt",
        crosscheck=-0.1068,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # bisulfate -- what is left in the nitric retort
    'O=S(=O)([O-])O': AqueousIon(
        smiles='O=S(=O)([O-])O', formula='HSO4-',
        cas='14996-02-2', name='Bisulfate ion',
        charge=-1, elements={'H': 1, 'S': 1, 'O': 4},
        Hf=-887.3, Gf=-755.9, S0=131.8, Cp=-84.0,
        purpose='bisulfate -- what is left in the nitric retort',
        crosscheck=-0.2034,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # sulfite
    '[O-][S+]([O-])[O-]': AqueousIon(
        smiles='[O-][S+]([O-])[O-]', formula='SO3-2',
        cas='14265-45-3', name='Sulfite ion',
        charge=-2, elements={'S': 1, 'O': 3},
        Hf=-635.5, Gf=-486.5, S0=-29.0, Cp=None,
        purpose='sulfite',
        crosscheck=0.0443,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # bisulfite
    '[O-][S+]([O-])O': AqueousIon(
        smiles='[O-][S+]([O-])O', formula='HSO3-',
        cas='15181-46-1', name='Bisulfite ion',
        charge=-1, elements={'H': 1, 'S': 1, 'O': 3},
        Hf=-626.2, Gf=-527.7, S0=139.7, Cp=None,
        purpose='bisulfite',
        crosscheck=-0.1578,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # thiosulfate -- photographic hypo
    'O=S(=O)([O-])[S-]': AqueousIon(
        smiles='O=S(=O)([O-])[S-]', formula='S2O3-2',
        cas='14383-50-7', name='Thiosulfate ion',
        charge=-2, elements={'S': 2, 'O': 3},
        Hf=-652.3, Gf=-522.5, S0=67.0, Cp=None,
        purpose='thiosulfate -- photographic hypo',
        crosscheck=-0.104,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # carbonate -- potash, soda ash, calcite
    'O=C([O-])[O-]': AqueousIon(
        smiles='O=C([O-])[O-]', formula='CO3-2',
        cas='3812-32-6', name='Carbonate ion',
        charge=-2, elements={'C': 1, 'O': 3},
        Hf=-677.1, Gf=-527.8, S0=-56.9, Cp=None,
        purpose='carbonate -- potash, soda ash, calcite',
        crosscheck=-0.103,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # bicarbonate
    'O=C([O-])O': AqueousIon(
        smiles='O=C([O-])O', formula='HCO3-',
        cas='71-52-3', name='Bicarbonate ion',
        charge=-1, elements={'H': 1, 'C': 1, 'O': 3},
        Hf=-692.0, Gf=-586.8, S0=91.2, Cp=None,
        purpose='bicarbonate',
        crosscheck=-0.0469,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # phosphate
    'O=P([O-])([O-])[O-]': AqueousIon(
        smiles='O=P([O-])([O-])[O-]', formula='PO4-3',
        cas='14265-44-2', name='Phosphate ion',
        charge=-3, elements={'P': 1, 'O': 4},
        Hf=-1277.4, Gf=-1018.7, S0=-220.5, Cp=None,
        purpose='phosphate',
        crosscheck=-0.1091,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # hydrogen phosphate
    'O=P([O-])([O-])O': AqueousIon(
        smiles='O=P([O-])([O-])O', formula='HPO4-2',
        cas='14066-19-4', name='Hydrogen phosphate ion',
        charge=-2, elements={'H': 1, 'P': 1, 'O': 4},
        Hf=-1292.1, Gf=-1089.2, S0=-33.5, Cp=None,
        purpose='hydrogen phosphate',
        crosscheck=-0.1551,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # dihydrogen phosphate
    'O=P([O-])(O)O': AqueousIon(
        smiles='O=P([O-])(O)O', formula='H2PO4-',
        cas='14066-20-7', name='Dihydrogen phosphate ion',
        charge=-1, elements={'H': 2, 'P': 1, 'O': 4},
        Hf=-1296.3, Gf=-1130.2, S0=90.4, Cp=None,
        purpose='dihydrogen phosphate',
        crosscheck=-0.0143,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # hypochlorite -- bleach
    '[O-]Cl': AqueousIon(
        smiles='[O-]Cl', formula='ClO-',
        cas='14380-61-1', name='Hypochlorite ion',
        charge=-1, elements={'Cl': 1, 'O': 1},
        Hf=-107.1, Gf=-36.8, S0=42.0, Cp=None,
        purpose='hypochlorite -- bleach',
        crosscheck=-0.5106,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # chlorate
    '[O-][Cl+2]([O-])[O-]': AqueousIon(
        smiles='[O-][Cl+2]([O-])[O-]', formula='ClO3-',
        cas='14866-68-3', name='Chlorate ion',
        charge=-1, elements={'Cl': 1, 'O': 3},
        Hf=-104.0, Gf=-8.0, S0=162.3, Cp=None,
        purpose='chlorate',
        crosscheck=-0.1236,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # perchlorate
    '[O-][Cl+3]([O-])([O-])[O-]': AqueousIon(
        smiles='[O-][Cl+3]([O-])([O-])[O-]', formula='ClO4-',
        cas='14797-73-0', name='Perchlorate ion',
        charge=-1, elements={'Cl': 1, 'O': 4},
        Hf=-129.3, Gf=-8.5, S0=182.0, Cp=None,
        purpose='perchlorate',
        crosscheck=-0.0402,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # bromate
    '[O-][Br+2]([O-])[O-]': AqueousIon(
        smiles='[O-][Br+2]([O-])[O-]', formula='BrO3-',
        cas='15541-45-4', name='Bromate ion',
        charge=-1, elements={'Br': 1, 'O': 3},
        Hf=-67.1, Gf=18.6, S0=161.7, Cp=None,
        purpose='bromate',
        crosscheck=-0.033,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # iodate
    '[O-][I+2]([O-])[O-]': AqueousIon(
        smiles='[O-][I+2]([O-])[O-]', formula='IO3-',
        cas='15454-31-6', name='Iodate ion',
        charge=-1, elements={'I': 1, 'O': 3},
        Hf=-221.3, Gf=-128.0, S0=118.4, Cp=None,
        purpose='iodate',
        crosscheck=0.0387,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # permanganate
    '[O]=[Mn](=[O])(=[O])[O-]': AqueousIon(
        smiles='[O]=[Mn](=[O])(=[O])[O-]', formula='MnO4-',
        cas='14333-13-2', name='Permanganate ion',
        charge=-1, elements={'Mn': 1, 'O': 4},
        Hf=-541.4, Gf=-447.2, S0=191.2, Cp=-82.0,
        purpose='permanganate',
        crosscheck=-0.1794,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # chromate -- chrome yellow
    '[O]=[Cr](=[O])([O-])[O-]': AqueousIon(
        smiles='[O]=[Cr](=[O])([O-])[O-]', formula='CrO4-2',
        cas='13907-45-4', name='Chromate ion',
        charge=-2, elements={'Cr': 1, 'O': 4},
        Hf=-881.2, Gf=-727.8, S0=50.2, Cp=None,
        purpose='chromate -- chrome yellow',
        crosscheck=-0.0578,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # aluminate
    '[O]=[Al][O-]': AqueousIon(
        smiles='[O]=[Al][O-]', formula='AlO2-',
        cas='20653-98-9', name='Aluminate ion',
        charge=-1, elements={'Al': 1, 'O': 2},
        Hf=-930.9, Gf=-830.9, S0=-36.8, Cp=None,
        purpose='aluminate',
        crosscheck=-0.074,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # formate
    'O=C[O-]': AqueousIon(
        smiles='O=C[O-]', formula='CHOO-',
        cas='71-47-6', name='Formate ion',
        charge=-1, elements={'C': 1, 'H': 1, 'O': 2},
        Hf=-425.6, Gf=-351.0, S0=92.0, Cp=-87.9,
        purpose='formate',
        crosscheck=0.1818,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # acetate
    'CC(=O)[O-]': AqueousIon(
        smiles='CC(=O)[O-]', formula='CH3COO-',
        cas='71-50-1', name='Acetate ion',
        charge=-1, elements={'C': 2, 'H': 3, 'O': 2},
        Hf=-486.0, Gf=-369.3, S0=86.6, Cp=-6.3,
        purpose='acetate',
        crosscheck=0.0041,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
    # oxalate -- and calcium oxalate is a stone
    'O=C([O-])C(=O)[O-]': AqueousIon(
        smiles='O=C([O-])C(=O)[O-]', formula='C2O4-2',
        cas='338-70-5', name='Oxalate ion',
        charge=-2, elements={'C': 2, 'O': 4},
        Hf=-825.1, Gf=-673.9, S0=45.6, Cp=None,
        purpose='oxalate -- and calcium oxalate is a stone',
        crosscheck=0.0678,
        source="CRC 'Thermodynamic Properties of Aqueous Ions', conventional Gf(H+,aq) = 0 basis, via the data file shipped with chemicals 1.5.2",
    ),
}


def aqueous_ion(smiles: str) -> AqueousIon | None:
    """The record for a canonical ion SMILES, or None. Never raises."""
    return AQUEOUS_IONS.get(smiles)


def worst_crosscheck() -> tuple:
    """(smiles, residual kJ/mol) for the entry that closes least well.

    Exposed so a test pins the residual rather than the docstring claiming it.
    """
    worst = max(AQUEOUS_IONS.values(), key=lambda r: abs(r.crosscheck))
    return worst.smiles, worst.crosscheck
