"""Layer 1 -- MINERALS: the other half of the floor, and a verdict on lattices.

GENERATED by ``tools/build_mineral_data.py`` from ``chemicals`` 1.5.2. Do not
hand-edit: regenerate. That script's docstring carries the argument and the
measurements; the short version is below.

## A LATTICE IS NOT A MOLECULE, AND THE FUSION LAW SAYS SO OUT LOUD

"Make it from natural things" bottoms out at an element or a mineral, and a
mineral is an ionic lattice. The engine's only route from a solid into solution
is the ideal-solubility FUSION LAW, ``ln a_sat = -(Hfus/R)(1/T - 1/Tm)``, and
applied to an ionic lattice that law is wrong by up to three orders of magnitude
IN BOTH DIRECTIONS -- measured against tabulated solubility at 298 K:

    NaCl    407x too INSOLUBLE       KNO3     2.6x too SOLUBLE
    K2CO3   585x too insoluble       CaCO3   11x   too soluble
    Na2CO3  251x too insoluble

6,400x of spread across five salts, with the sign flipping. Not a bias a factor
could absorb -- the wrong law. Tm and Hfus describe lattice -> MELT; dissolution
is lattice -> HYDRATED IONS, and the hydration energy appears in neither.

**Hence: this module is REFERENCE DATA, not a provider tier.** The solid-basis
Hf/Gf/S0 here is what a solubility product or a calcination
(CaCO3(s) -> CaO(s) + CO2(g)) would be computed from -- both on the backlog --
and ``thermochemistry`` REFUSES a lattice SMILES by name rather than handing it
to a dissolution law that is measurably wrong. What a mineral in a flask
actually is, is its IONS, and that already works: nitrate is priced from nitric
acid's pKa, sulfate from sulfuric acid's, and a spectator cation is a zero
reference that cancels out of every equilibrium it appears in.

``validation/game_gates.py`` re-measures the bound above, so the verdict cannot
go stale if a solubility mechanic ever lands.

## Provenance

dGf is DERIVED from dHf and S0 against the CRC element reference states in
``element_data`` -- the same basis, which is what makes closing the element class
pay for itself here. Both halves of an entry come from the SAME database or the
entry is refused; that rule bites on FeSO4, whose S0s is 107.5 J/(mol K) from
CRC and 120.93 from WEBBOOK, 13.4 apart and worth 4 kJ/mol in Gf. Every
estimated method is excluded explicitly.
"""

from __future__ import annotations

from typing import NamedTuple


class MineralRecord(NamedTuple):
    """One mineral, on the SOLID basis, plus the ions it dissolves into.

    ``Hf_solid``/``Gf_solid`` are NOT on the ideal-gas basis every ``ThermoData``
    uses, which is exactly why this is a separate type in a separate module: a
    solid-basis number wearing a ThermoData would be silently shifted by
    ``standard_state`` and silently dissolved by the fusion law.
    """

    name: str
    cas: str
    ions: tuple                    # canonical SMILES of the dissolved ions
    formula: dict                  # element counts of one formula unit
    purpose: str                   # what a chain wants it FOR
    Hf_solid: float                # kJ/mol, crystalline, 298.15 K
    Gf_solid: float                # kJ/mol, DERIVED
    S0_solid: float                # J/(mol K), absolute
    Tm: float | None               # K -- MELTING is what a fusion pair is for
    Hfus: float | None             # kJ/mol
    source: str
    physical_source: str
    # (fusion-law prediction mol/L, measured mol/L, ratio) where a measured
    # solubility exists. The verdict above, per species, as data.
    fusion_law_bound: tuple | None
    solubility_note: str | None



MINERALS: dict[str, MineralRecord] = {
    # limestone -- calcination to quicklime
    'calcite': MineralRecord(
        name='calcite', cas='471-34-1',
        ions=('[Ca+2]', 'O=C([O-])[O-]'),
        formula={'Ca': 1, 'C': 1, 'O': 3},
        purpose='limestone -- calcination to quicklime',
        Hf_solid=-1207.6, Gf_solid=-1129.07, S0_solid=91.7,
        Tm=1073.15, Hfus=36.0,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=(0.001543, 0.00014, 11.02131),
        solubility_note='14 mg/L (CRC), MW 100.09',
    ),
    # the product of calcining limestone
    'quicklime': MineralRecord(
        name='quicklime', cas='1305-78-8',
        ions=('[Ca+2]', '[O-2]'),
        formula={'Ca': 1, 'O': 1},
        purpose='the product of calcining limestone',
        Hf_solid=-634.9, Gf_solid=-603.27, S0_solid=38.1,
        Tm=2886.15, Hfus=80.0,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # quicklime + water; a cheap strong base
    'slaked lime': MineralRecord(
        name='slaked lime', cas='1305-62-0',
        ions=('[Ca+2]', '[OH-]', '[OH-]'),
        formula={'Ca': 1, 'O': 2, 'H': 2},
        purpose='quicklime + water; a cheap strong base',
        Hf_solid=-985.2, Gf_solid=-897.51, S0_solid=83.4,
        Tm=853.15, Hfus=None,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=COMMON_CHEMISTRY',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # dry-distils to the H2SO4 SEED that bootstraps chain 2
    'green vitriol': MineralRecord(
        name='green vitriol', cas='7720-78-7',
        ions=('[Fe+2]', 'O=S(=O)([O-])[O-]'),
        formula={'Fe': 1, 'S': 1, 'O': 4},
        purpose='dry-distils to the H2SO4 SEED that bootstraps chain 2',
        Hf_solid=-928.4, Gf_solid=-820.38, S0_solid=107.5,
        Tm=None, Hfus=None,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='no measured Tm or Hfus in any source consulted',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # wood ash -- the lye of chain 1's detour A
    'potash': MineralRecord(
        name='potash', cas='584-08-7',
        ions=('[K+]', '[K+]', 'O=C([O-])[O-]'),
        formula={'K': 2, 'C': 1, 'O': 3},
        purpose="wood ash -- the lye of chain 1's detour A",
        Hf_solid=-1151.0, Gf_solid=-1065.31, S0_solid=155.5,
        Tm=1172.15, Hfus=27.6,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=(0.013733, 8.03, 0.00171),
        solubility_note='1110 g/L (CRC), MW 138.21',
    ),
    # the sodium twin of potash
    'soda ash': MineralRecord(
        name='soda ash', cas='497-19-8',
        ions=('[Na+]', '[Na+]', 'O=C([O-])[O-]'),
        formula={'Na': 2, 'C': 1, 'O': 3},
        purpose='the sodium twin of potash',
        Hf_solid=-1130.7, Gf_solid=-1046.89, S0_solid=135.0,
        Tm=1129.15, Hfus=29.7,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=(0.0082, 2.06, 0.00398),
        solubility_note='218 g/L (CRC), MW 105.99',
    ),
    # the nitre bed -- chain 2's nitrogen carrier
    'saltpetre': MineralRecord(
        name='saltpetre', cas='7757-79-1',
        ions=('[K+]', 'O=[N+]([O-])[O-]'),
        formula={'K': 1, 'N': 1, 'O': 3},
        purpose="the nitre bed -- chain 2's nitrogen carrier",
        Hf_solid=-494.6, Gf_solid=-394.66, S0_solid=133.1,
        Tm=607.15, Hfus=9.6,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=(8.958898, 3.51, 2.55239),
        solubility_note='355 g/L (CRC), MW 101.10',
    ),
    # brine, and the chlor-alkali route
    'rock salt': MineralRecord(
        name='rock salt', cas='7647-14-5',
        ions=('[Na+]', '[Cl-]'),
        formula={'Na': 1, 'Cl': 1},
        purpose='brine, and the chlor-alkali route',
        Hf_solid=-411.2, Gf_solid=-384.14, S0_solid=72.1,
        Tm=1073.85, Hfus=28.16,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=(0.015118, 6.15, 0.00246),
        solubility_note='359 g/L (CRC), MW 58.44',
    ),
    # the neutralised residue of a sulfuric process
    "Glauber's salt": MineralRecord(
        name="Glauber's salt", cas='7757-82-6',
        ions=('[Na+]', '[Na+]', 'O=S(=O)([O-])[O-]'),
        formula={'Na': 2, 'S': 1, 'O': 4},
        purpose='the neutralised residue of a sulfuric process',
        Hf_solid=-1387.1, Gf_solid=-1269.18, S0_solid=149.6,
        Tm=1157.15, Hfus=23.85,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # what is LEFT in the retort after HNO3 is distilled off saltpetre
    'potassium bisulfate': MineralRecord(
        name='potassium bisulfate', cas='7646-93-7',
        ions=('[K+]', 'O=S(=O)([O-])O'),
        formula={'K': 1, 'S': 1, 'O': 4, 'H': 1},
        purpose='what is LEFT in the retort after HNO3 is distilled off saltpetre',
        Hf_solid=-1160.6, Gf_solid=-1031.07, S0_solid=138.1,
        Tm=473.15, Hfus=None,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # the lye potash becomes with slaked lime
    'caustic potash': MineralRecord(
        name='caustic potash', cas='1310-58-3',
        ions=('[K+]', '[OH-]'),
        formula={'K': 1, 'O': 1, 'H': 1},
        purpose='the lye potash becomes with slaked lime',
        Hf_solid=-424.6, Gf_solid=-379.45, S0_solid=81.2,
        Tm=679.15, Hfus=7.9,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # lye
    'caustic soda': MineralRecord(
        name='caustic soda', cas='1310-73-2',
        ions=('[Na+]', '[OH-]'),
        formula={'Na': 1, 'O': 1, 'H': 1},
        purpose='lye',
        Hf_solid=-425.8, Gf_solid=-379.63, S0_solid=64.4,
        Tm=596.15, Hfus=6.6,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # a second vitriol, for contrast
    'blue vitriol': MineralRecord(
        name='blue vitriol', cas='7758-98-7',
        ions=('[Cu+2]', 'O=S(=O)([O-])[O-]'),
        formula={'Cu': 1, 'S': 1, 'O': 4},
        purpose='a second vitriol, for contrast',
        Hf_solid=-771.4, Gf_solid=-662.13, S0_solid=109.2,
        Tm=863.15, Hfus=None,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=COMMON_CHEMISTRY',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # AgCl -- the canonical 'it went cloudy' precipitate
    'chlorargyrite': MineralRecord(
        name='chlorargyrite', cas='7783-90-6',
        ions=('[Ag+]', '[Cl-]'),
        formula={'Ag': 1, 'Cl': 1},
        purpose="AgCl -- the canonical 'it went cloudy' precipitate",
        Hf_solid=-127.0, Gf_solid=-109.75, S0_solid=96.3,
        Tm=728.15, Hfus=13.054,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # AgBr -- the photographic halide
    'bromargyrite': MineralRecord(
        name='bromargyrite', cas='7785-23-1',
        ions=('[Ag+]', '[Br-]'),
        formula={'Ag': 1, 'Br': 1},
        purpose='AgBr -- the photographic halide',
        Hf_solid=-100.4, Gf_solid=-96.94, S0_solid=107.1,
        Tm=703.15, Hfus=9.163,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # AgI -- the least soluble silver halide
    'iodargyrite': MineralRecord(
        name='iodargyrite', cas='7783-96-2',
        ions=('[Ag+]', '[I-]'),
        formula={'Ag': 1, 'I': 1},
        purpose='AgI -- the least soluble silver halide',
        Hf_solid=-61.8, Gf_solid=-66.23, S0_solid=115.5,
        Tm=831.15, Hfus=9.414,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # AgNO3 -- the SOLUBLE reagent; it must NOT precipitate, which is a test
    'lunar caustic': MineralRecord(
        name='lunar caustic', cas='7761-88-8',
        ions=('[Ag+]', 'O=[N+]([O-])[O-]'),
        formula={'Ag': 1, 'N': 1, 'O': 3},
        purpose='AgNO3 -- the SOLUBLE reagent; it must NOT precipitate, which is a test',
        Hf_solid=-124.4, Gf_solid=-33.37, S0_solid=140.9,
        Tm=483.15, Hfus=11.72,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # BaSO4 -- gravimetric sulfate, and stone-insoluble
    'barite': MineralRecord(
        name='barite', cas='7727-43-7',
        ions=('[Ba+2]', 'O=S(=O)([O-])[O-]'),
        formula={'Ba': 1, 'S': 1, 'O': 4},
        purpose='BaSO4 -- gravimetric sulfate, and stone-insoluble',
        Hf_solid=-1473.2, Gf_solid=-1362.05, S0_solid=132.2,
        Tm=1853.15, Hfus=40.0,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # the soluble barium reagent barite is precipitated from
    'barium chloride': MineralRecord(
        name='barium chloride', cas='10361-37-2',
        ions=('[Ba+2]', '[Cl-]', '[Cl-]'),
        formula={'Ba': 1, 'Cl': 2},
        purpose='the soluble barium reagent barite is precipitated from',
        Hf_solid=-855.0, Gf_solid=-806.73, S0_solid=123.7,
        Tm=1234.15, Hfus=15.85,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # CaSO4 -- what M1's three acid-displacement steps drop (as the anhydrate)
    'anhydrite': MineralRecord(
        name='anhydrite', cas='7778-18-9',
        ions=('[Ca+2]', 'O=S(=O)([O-])[O-]'),
        formula={'Ca': 1, 'S': 1, 'O': 4},
        purpose="CaSO4 -- what M1's three acid-displacement steps drop (as the anhydrate)",
        Hf_solid=-1434.5, Gf_solid=-1321.92, S0_solid=106.5,
        Tm=1733.15, Hfus=28.0,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # PbSO4
    'anglesite': MineralRecord(
        name='anglesite', cas='7446-14-2',
        ions=('[Pb+2]', 'O=S(=O)([O-])[O-]'),
        formula={'Pb': 1, 'S': 1, 'O': 4},
        purpose='PbSO4',
        Hf_solid=-920.0, Gf_solid=-813.02, S0_solid=148.5,
        Tm=1360.15, Hfus=40.2,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # PbI2 -- the golden rain
    'lead iodide': MineralRecord(
        name='lead iodide', cas='10101-63-0',
        ions=('[Pb+2]', '[I-]', '[I-]'),
        formula={'Pb': 1, 'I': 2},
        purpose='PbI2 -- the golden rain',
        Hf_solid=-175.5, Gf_solid=-173.71, S0_solid=174.9,
        Tm=683.15, Hfus=23.4,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # CaF2 -- and the source of HF
    'fluorite': MineralRecord(
        name='fluorite', cas='7789-75-5',
        ions=('[Ca+2]', '[F-]', '[F-]'),
        formula={'Ca': 1, 'F': 2},
        purpose='CaF2 -- and the source of HF',
        Hf_solid=-1228.0, Gf_solid=-1175.56, S0_solid=68.5,
        Tm=1691.15, Hfus=30.0,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # ZnS -- the zinc ore, and a sulfide precipitate
    'sphalerite': MineralRecord(
        name='sphalerite', cas='1314-98-3',
        ions=('[Zn+2]', '[S-2]'),
        formula={'Zn': 1, 'S': 1},
        purpose='ZnS -- the zinc ore, and a sulfide precipitate',
        Hf_solid=-206.0, Gf_solid=-201.23, S0_solid=57.7,
        Tm=2100.15, Hfus=30.0,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG; Hfus=CRC',
        fusion_law_bound=None,
        solubility_note=None,
    ),
    # Mg(OH)2 -- milk of magnesia
    'brucite': MineralRecord(
        name='brucite', cas='1309-42-8',
        ions=('[Mg+2]', '[OH-]', '[OH-]'),
        formula={'Mg': 1, 'O': 2, 'H': 2},
        purpose='Mg(OH)2 -- milk of magnesia',
        Hf_solid=-924.5, Gf_solid=-833.44, S0_solid=63.2,
        Tm=623.15, Hfus=None,
        source='Hfs and S0s both from CRC via chemicals 1.5.2; Gf DERIVED against the CRC element reference states',
        physical_source='Tm=CRC_INORG',
        fusion_law_bound=None,
        solubility_note=None,
    ),
}


def lattice_smiles() -> frozenset:
    """Every ion-by-ion SMILES that names a mineral in this table.

    ``thermochemistry`` uses it for nothing -- a multi-fragment charged SMILES is
    already refused by the net-charge guard. It is here so a REFUSAL can name
    what the caller probably meant: "that is calcite, whose lattice this engine
    cannot dissolve; charge its ions".
    """
    return frozenset(r.ions for r in MINERALS.values())


def by_ions() -> dict:
    """Reverse index: the tuple of dissolved ions -> the mineral record."""
    return {r.ions: r for r in MINERALS.values()}
