"""Layer 1 -- MEASURED physical constants, keyed by canonical SMILES.

GENERATED by ``tools/build_physical_data.py`` from ``chemicals`` 1.5.2.
Do not hand-edit: regenerate.

Primarily this table exists to feed Wilson-Jasperson, which takes Tb as an input
and returns Tc and Pc. That is the coverage gap it closes: a species Joback
cannot fragment has no Tb from anywhere, and without a Tb there is no
vapour-pressure curve, no acentric factor, and no way to reach a Benson
formation half however well Benson prices it. Where measured critical constants
also exist they are here too, and they outrank the estimate.

**Nothing here is a group-contribution estimate, and that was not free.**
``chemicals`` serves Joback predictions through the same accessor as its measured
compilations. For metformin the ONLY Tb source it offers is ``JOBACK``, returning
609.52 K -- bit-identical to what this project's own Joback implementation
computes from the same groups, because it is the same method. Looking that up
would have closed a coverage gap by relabelling our own estimate as measured
data. Every estimated method is excluded and the species refused instead, which
is why metformin and saccharin carry no Tb below rather than a
confident-looking number.

## Two tiers, and why the distinction is kept on every value

``experimental``  critically evaluated measurement (IUPAC, CRC, MATTHEWS,
                  WEBBOOK, HEOS, Common Chemistry, Open Notebook melting points)

``compilation``   published, widely used, and NOT auditable to a measurement.
                  ``chemicals`` says of YAWS "no data points are sourced in the
                  work"; PSRK mixes experimental with estimated; PINAMARTINES is
                  supporting material from an equation-of-state paper. The
                  decisive check is empirical -- PINAMARTINES gives saccharin a
                  critical temperature of 968 K, and saccharin decomposes near
                  500 K without ever boiling, so that is not a measurement of
                  anything.

Tc/Pc/Vc are taken from the EXPERIMENTAL TIER ONLY. Where none exists the record
falls to Wilson-Jasperson and Fedors, and that is the deliberate choice: their
error is known, because ``validation/physical_estimation.py`` measures it, while
a number of unrecorded origin may itself be a group-contribution estimate from a
method we cannot inspect. **Tb gets no such choice** -- Wilson-Jasperson takes it
as an input and nothing in this project estimates a boiling point -- so a
compilation-tier Tb is accepted where it is the only source and stamped as such.
MDI is the case that matters: its Tb comes from YAWS.

Tc and Pc are taken as a PAIR or not at all. They combine into the acentric
factor, omega = (ln(P_atm/Pc) - f0(Tb/Tc)) / f1(Tb/Tc), so a measured Tc beside
an estimated Pc would mix two bases inside one derived number -- the same rule
that forbids an ATCT enthalpy beside a CRC entropy inside one formation entry.

``omega_reference`` is recorded for CROSS-CHECKING ONLY and never used to build a
record. This project derives omega by inverting Lee-Kesler at Tb so the fitted
vapour-pressure curve passes through the boiling point exactly; a tabulated omega
is therefore an INDEPENDENT check on that derivation, and independence is its
entire value. Entries whose only source is ``ACENTRIC_DEFINITION`` are dropped,
because that is omega back-computed from a vapour pressure and so is not
independent of the thing being checked.

WHAT WAS LOOKED UP AND REJECTED, with the reason:
#   * saccharin: Tb REJECTED -- no source at all. Wilson-Jasperson takes Tb as an input, so this species gets no Tc/Pc from that route and cannot reach a Benson formation half. Its Tm is still kept below where one exists: a solid that never boils still crystallises.
#   * metformin: Tb REJECTED -- only estimated sources offered (['JOBACK']). Wilson-Jasperson takes Tb as an input, so this species gets no Tc/Pc from that route and cannot reach a Benson formation half. Its Tm is still kept below where one exists: a solid that never boils still crystallises.
#   * glyphosate: Tb REJECTED -- no source at all. Wilson-Jasperson takes Tb as an input, so this species gets no Tc/Pc from that route and cannot reach a Benson formation half. Its Tm is still kept below where one exists: a solid that never boils still crystallises.
#   * formic acid: Tc/Pc SPLIT -- one measured and one not (Tc=(588.0, 'IUPAC', 'experimental'), Pc=None); taking neither, because they combine into the acentric factor and must share a basis
#   * thiourea: Tb REJECTED -- no source at all. Wilson-Jasperson takes Tb as an input, so this species gets no Tc/Pc from that route and cannot reach a Benson formation half. Its Tm is still kept below where one exists: a solid that never boils still crystallises.
#   * p-toluenesulfonic acid: Tb REJECTED -- no source at all. Wilson-Jasperson takes Tb as an input, so this species gets no Tc/Pc from that route and cannot reach a Benson formation half. Its Tm is still kept below where one exists: a solid that never boils still crystallises.
"""

from __future__ import annotations

from typing import NamedTuple


class Measured(NamedTuple):
    """One value, the database it came from, and how far that can be trusted."""

    value: float
    database: str
    tier: str                       # "experimental" | "compilation"


class MeasuredPhysical(NamedTuple):
    """Everything looked up for one species; ``None`` where nothing qualified.

    Tb/Tm/Tc in K, Hfus in kJ/mol, Pc in bar, Vc in cm3/mol. Each is a
    ``Measured`` rather than a bare float so provenance travels with the number
    instead of being reconstructed later by a caller who can only guess.
    """

    Tb: Measured | None = None
    Tm: Measured | None = None
    Hfus: Measured | None = None
    Tc: Measured | None = None
    Pc: Measured | None = None
    Vc: Measured | None = None
    omega_reference: Measured | None = None


MEASURED_PHYSICAL: dict[str, MeasuredPhysical] = {
    # 2-methylpropanal  (CAS 78-84-2; Joback: complete)
    'CC(C)C=O': MeasuredPhysical(
        Tb=Measured(337.25, 'CRC_ORG', 'experimental'),
        Tm=Measured(208.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=Measured(544.0, 'IUPAC', 'experimental'),
        Pc=Measured(51.0, 'IUPAC', 'experimental'),
        Vc=Measured(283.0, 'CRC', 'experimental'),
        omega_reference=Measured(0.325, 'PSRK', 'compilation'),
    ),
    # N,N-dimethylformamide  (CAS 68-12-2; Joback: unfragmentable)
    'CN(C)C=O': MeasuredPhysical(
        Tb=Measured(425.95, 'CRC_ORG', 'experimental'),
        Tm=Measured(212.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(7.9, 'CRC', 'experimental'),
        Tc=Measured(649.6, 'IUPAC', 'experimental'),
        Pc=Measured(44.0, 'CRC', 'experimental'),
        Vc=Measured(262.0, 'IUPAC', 'experimental'),
        omega_reference=Measured(0.389, 'PSRK', 'compilation'),
    ),
    # N-methylformamide  (CAS 123-39-7; Joback: unfragmentable)
    'CNC=O': MeasuredPhysical(
        Tb=Measured(459.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(251.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=Measured(0.492, 'PSRK', 'compilation'),
    ),
    # acetic anhydride  (CAS 108-24-7; Joback: unfragmentable)
    'CC(=O)OC(C)=O': MeasuredPhysical(
        Tb=Measured(412.65, 'CRC_ORG', 'experimental'),
        Tm=Measured(200.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(10.5, 'CRC', 'experimental'),
        Tc=Measured(606.0, 'IUPAC', 'experimental'),
        Pc=Measured(40.0, 'IUPAC', 'experimental'),
        Vc=Measured(294.0, 'CRC', 'experimental'),
        omega_reference=Measured(0.4419, 'PSRK', 'compilation'),
    ),
    # benzaldehyde  (CAS 100-52-7; Joback: unfragmentable)
    'O=Cc1ccccc1': MeasuredPhysical(
        Tb=Measured(451.85, 'CRC_ORG', 'experimental'),
        Tm=Measured(216.9, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(9.32, 'CRC', 'experimental'),
        Tc=Measured(695.0, 'IUPAC', 'experimental'),
        Pc=Measured(47.0, 'IUPAC', 'experimental'),
        Vc=None,
        omega_reference=Measured(0.32, 'PSRK', 'compilation'),
    ),
    # benzenesulfonyl chloride  (CAS 98-09-9; Joback: unfragmentable)
    'O=S(=O)(Cl)c1ccccc1': MeasuredPhysical(
        Tb=Measured(525.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(288.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=None,
    ),
    # benzoic anhydride  (CAS 93-97-0; Joback: unfragmentable)
    'O=C(OC(=O)c1ccccc1)c1ccccc1': MeasuredPhysical(
        Tb=Measured(633.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(315.4, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=None,
    ),
    # butanal  (CAS 123-72-8; Joback: complete)
    'CCCC=O': MeasuredPhysical(
        Tb=Measured(347.95, 'CRC_ORG', 'experimental'),
        Tm=Measured(175.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(10.77, 'CRC', 'experimental'),
        Tc=Measured(537.0, 'IUPAC', 'experimental'),
        Pc=Measured(43.2, 'IUPAC', 'experimental'),
        Vc=Measured(258.0, 'IUPAC', 'experimental'),
        omega_reference=Measured(0.352, 'PSRK', 'compilation'),
    ),
    # carbon disulfide  (CAS 75-15-0; Joback: unfragmentable)
    'S=C=S': MeasuredPhysical(
        Tb=Measured(319.35, 'CRC_ORG', 'experimental'),
        Tm=Measured(161.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(4.39, 'CRC', 'experimental'),
        Tc=Measured(552.0, 'MATTHEWS', 'experimental'),
        Pc=Measured(79.0335, 'MATTHEWS', 'experimental'),
        Vc=Measured(160.0, 'MATTHEWS', 'experimental'),
        omega_reference=Measured(0.115, 'PSRK', 'compilation'),
    ),
    # dimethyl sulfone  (CAS 67-71-0; Joback: unfragmentable)
    'CS(C)(=O)=O': MeasuredPhysical(
        Tb=Measured(511.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(382.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(18.3, 'CRC', 'experimental'),
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=None,
    ),
    # dimethyl sulfoxide  (CAS 67-68-5; Joback: unfragmentable)
    'CS(C)=O': MeasuredPhysical(
        Tb=Measured(465.05, 'CRC_ORG', 'experimental'),
        Tm=Measured(291.55, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(14.37, 'CRC', 'experimental'),
        Tc=Measured(707.0, 'CRC', 'experimental'),
        Pc=Measured(46.0, 'CRC', 'experimental'),
        Vc=Measured(213.0, 'IUPAC', 'experimental'),
        omega_reference=Measured(0.3319, 'PSRK', 'compilation'),
    ),
    # diphenyl sulfoxide  (CAS 945-51-7; Joback: unfragmentable)
    'O=S(c1ccccc1)c1ccccc1': MeasuredPhysical(
        Tb=Measured(613.15, 'COMMON_CHEMISTRY', 'experimental'),
        Tm=Measured(344.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=None,
    ),
    # ethylene  (CAS 74-85-1; Joback: complete)
    'C=C': MeasuredPhysical(
        Tb=Measured(169.378648434, 'HEOS', 'experimental'),
        Tm=Measured(104.05, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(3.35, 'CRC', 'experimental'),
        Tc=Measured(282.35, 'HEOS', 'experimental'),
        Pc=Measured(50.418, 'HEOS', 'experimental'),
        Vc=Measured(130.945481716, 'HEOS', 'experimental'),
        omega_reference=Measured(0.0866, 'HEOS', 'experimental'),
    ),
    # formamide  (CAS 75-12-7; Joback: unfragmentable)
    'NC=O': MeasuredPhysical(
        Tb=Measured(490.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(275.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(8.44, 'CRC', 'experimental'),
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=Measured(0.4378, 'PSRK', 'compilation'),
    ),
    # formic acid  (CAS 64-18-6; Joback: unfragmentable)
    'O=CO': MeasuredPhysical(
        Tb=Measured(374.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(281.45, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(12.68, 'CRC', 'experimental'),
        Tc=None,
        Pc=None,
        Vc=Measured(115.89999999999999, 'CRC', 'experimental'),
        omega_reference=Measured(0.3222, 'PSRK', 'compilation'),
    ),
    # furfural  (CAS 98-01-1; Joback: unfragmentable)
    'O=Cc1ccco1': MeasuredPhysical(
        Tb=Measured(434.65, 'CRC_ORG', 'experimental'),
        Tm=Measured(235.9, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(14.37, 'CRC', 'experimental'),
        Tc=Measured(670.0, 'IUPAC', 'experimental'),
        Pc=Measured(55.1, 'IUPAC', 'experimental'),
        Vc=None,
        omega_reference=Measured(0.4522, 'PSRK', 'compilation'),
    ),
    # glyphosate  (CAS 1071-83-6; Joback: unfragmentable)
    'O=C(O)CNCP(=O)(O)O': MeasuredPhysical(
        Tb=None,
        Tm=Measured(462.65, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=None,
    ),
    # maleic anhydride  (CAS 108-31-6; Joback: unfragmentable)
    'O=C1C=CC(=O)O1': MeasuredPhysical(
        Tb=Measured(475.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(326.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(13.6, 'CRC', 'experimental'),
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=Measured(0.3897, 'PSRK', 'compilation'),
    ),
    # metformin  (CAS 657-24-9; Joback: partial)
    'CN(C)C(=N)N=C(N)N': MeasuredPhysical(
        Tb=None,
        Tm=Measured(497.65, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=None,
    ),
    # methanesulfonic acid  (CAS 75-75-2; Joback: unfragmentable)
    'CS(=O)(=O)O': MeasuredPhysical(
        Tb=Measured(561.0, 'YAWS', 'compilation'),
        Tm=Measured(293.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=None,
    ),
    # methyl formate  (CAS 107-31-3; Joback: unfragmentable)
    'COC=O': MeasuredPhysical(
        Tb=Measured(304.75, 'CRC_ORG', 'experimental'),
        Tm=Measured(173.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=Measured(487.2, 'IUPAC', 'experimental'),
        Pc=Measured(60.0, 'IUPAC', 'experimental'),
        Vc=Measured(172.0, 'IUPAC', 'experimental'),
        omega_reference=Measured(0.252, 'PSRK', 'compilation'),
    ),
    # methyl isocyanate  (CAS 624-83-9; Joback: partial)
    'CN=C=O': MeasuredPhysical(
        Tb=Measured(311.45, 'CRC_ORG', 'experimental'),
        Tm=Measured(210.65, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=Measured(0.2744, 'PSRK', 'compilation'),
    ),
    # methylene diphenyl diisocyanate  (CAS 101-68-8; Joback: partial)
    'O=C=Nc1ccc(Cc2ccc(N=C=O)cc2)cc1': MeasuredPhysical(
        Tb=Measured(609.0, 'YAWS', 'compilation'),
        Tm=Measured(310.75, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=Measured(0.6816, 'PSRK', 'compilation'),
    ),
    # p-anisaldehyde  (CAS 123-11-5; Joback: unfragmentable)
    'COc1ccc(C=O)cc1': MeasuredPhysical(
        Tb=Measured(528.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(273.65, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=None,
    ),
    # p-toluenesulfonic acid  (CAS 104-15-4; Joback: unfragmentable)
    'Cc1ccc(S(=O)(=O)O)cc1': MeasuredPhysical(
        Tb=None,
        Tm=Measured(377.65, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=None,
    ),
    # phenyl isocyanate  (CAS 103-71-9; Joback: partial)
    'O=C=Nc1ccccc1': MeasuredPhysical(
        Tb=Measured(439.45, 'CRC_ORG', 'experimental'),
        Tm=Measured(240.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=Measured(657.0, 'IUPAC', 'experimental'),
        Pc=Measured(40.0, 'IUPAC', 'experimental'),
        Vc=Measured(342.0, 'CRC', 'experimental'),
        omega_reference=Measured(0.2946, 'PSRK', 'compilation'),
    ),
    # phthalic anhydride  (CAS 85-44-9; Joback: unfragmentable)
    'O=C1OC(=O)c2ccccc21': MeasuredPhysical(
        Tb=Measured(558.45, 'CRC_ORG', 'experimental'),
        Tm=Measured(404.55, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=Measured(0.708, 'YAWS', 'compilation'),
    ),
    # piperonal  (CAS 120-57-0; Joback: unfragmentable)
    'O=Cc1ccc2c(c1)OCO2': MeasuredPhysical(
        Tb=Measured(536.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(310.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=None,
    ),
    # propene  (CAS 115-07-1; Joback: complete)
    'C=CC': MeasuredPhysical(
        Tb=Measured(225.530871246, 'HEOS', 'experimental'),
        Tm=Measured(88.075, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(3.003, 'CRC', 'experimental'),
        Tc=Measured(364.211, 'HEOS', 'experimental'),
        Pc=Measured(45.55, 'HEOS', 'experimental'),
        Vc=Measured(183.250870442, 'HEOS', 'experimental'),
        omega_reference=Measured(0.146, 'HEOS', 'experimental'),
    ),
    # propionic anhydride  (CAS 123-62-6; Joback: unfragmentable)
    'CCC(=O)OC(=O)CC': MeasuredPhysical(
        Tb=Measured(441.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(228.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=Measured(0.4876, 'PSRK', 'compilation'),
    ),
    # saccharin  (CAS 81-07-2; Joback: unfragmentable)
    'O=C1NS(=O)(=O)c2ccccc21': MeasuredPhysical(
        Tb=None,
        Tm=Measured(502.3, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=None,
    ),
    # salicylaldehyde  (CAS 90-02-8; Joback: unfragmentable)
    'O=Cc1ccccc1O': MeasuredPhysical(
        Tb=Measured(481.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(266.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=Measured(0.619, 'YAWS', 'compilation'),
    ),
    # succinic anhydride  (CAS 108-30-5; Joback: unfragmentable)
    'O=C1CCC(=O)O1': MeasuredPhysical(
        Tb=Measured(534.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(392.65, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(20.4, 'CRC', 'experimental'),
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=Measured(0.53, 'YAWS', 'compilation'),
    ),
    # sulfolane  (CAS 126-33-0; Joback: unfragmentable)
    'O=S1(=O)CCCC1': MeasuredPhysical(
        Tb=Measured(559.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(300.45, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=Measured(855.0, 'WEBBOOK', 'experimental'),
        Pc=Measured(72.9, 'WEBBOOK', 'experimental'),
        Vc=Measured(333.77837, 'WEBBOOK', 'experimental'),
        omega_reference=Measured(0.3463, 'PSRK', 'compilation'),
    ),
    # thiourea  (CAS 62-56-6; Joback: unfragmentable)
    'NC(N)=S': MeasuredPhysical(
        Tb=None,
        Tm=Measured(450.15, 'OPEN_NTBKM', 'experimental'),
        Hfus=Measured(14.0, 'CRC', 'experimental'),
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=Measured(0.3586, 'YAWS', 'compilation'),
    ),
    # triethyl phosphate  (CAS 78-40-0; Joback: unfragmentable)
    'CCOP(=O)(OCC)OCC': MeasuredPhysical(
        Tb=Measured(489.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(216.95, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=Measured(0.414, 'YAWS', 'compilation'),
    ),
    # vanillin  (CAS 121-33-5; Joback: unfragmentable)
    'COc1cc(C=O)ccc1O': MeasuredPhysical(
        Tb=Measured(558.15, 'CRC_ORG', 'experimental'),
        Tm=Measured(354.9, 'OPEN_NTBKM', 'experimental'),
        Hfus=None,
        Tc=None,
        Pc=None,
        Vc=None,
        omega_reference=Measured(0.757, 'YAWS', 'compilation'),
    ),
}
