"""T1 -- regenerate ``chemsim.reactions.template_data`` from the template table.

    python tools/build_templates.py            # writes the module
    python tools/build_templates.py --check    # verify only; a stale module fails
    python tools/build_templates.py --dry-run  # report only, write nothing

One input, ``data/templates/templates.psv``: 57 rows, one per template, every
field of ``ReactionTemplate`` in a column. The output is a generated Python
module, for the same reason ``ion_data``, ``mineral_data``, ``physical_data``,
``element_data``, ``shelf_data`` and the Benson tables are -- ``src/chemsim``
reads no file under ``data/`` at run time, because the package is installed from
``src`` alone.

## WHY A TEMPLATE STOPS BEING A FUNCTION

A template was a hand-written Python function with a docstring, a comment block
and a place in one of four modules. 240 catalog reaction classes at the
historical +3 to +5 per session is ~40 sessions, and T1.0 measured the ceiling:
174 of the 377 catalog steps are extractable and sit in an uncovered class. A
row is something an extractor can write; a function with a comment block is not.

## THE TWO CHECKS THIS SCRIPT IS, AND THE SECOND IS THE POINT

**The column set covers every field.** ``ReactionTemplate`` has thirteen fields
and this script reads them off the dataclass rather than listing them, so a new
field breaks the build until the table gains a column. That is P4's lesson,
which cost three milestones: ``TemplateSpec`` silently dropped ``orders``,
``solid_catalyst``, ``electrons`` and the three ``hammett_*`` fields, and the
assertion that found the last three was about the SET of fields rather than
about whichever field somebody remembered.

**Nothing outside the loader constructs a template.** The first half of T1
checked every row against the constructor it copied, field for field, and that
check retired with the constructors: they now READ their row, so comparing the
two would compare the table with itself. What holds the property that made the
old check worth having -- that adding a template is adding a row -- is the
inverse assertion, and it is again about a SET rather than about a file somebody
remembered: ``check_construction_sites`` walks all of ``src/chemsim`` and
refuses any ``ReactionTemplate(...)`` outside the three loaders that build a row
and the one that rebuilds a saved ``TemplateSpec``.

The constructors are still there and are still the public API -- ``catalyst=``,
``eta_a=``, ``A=`` and the rest are keyword arguments a caller can move, which a
row cannot be. What they no longer hold is data.
"""

from __future__ import annotations

import argparse
import ast
import os
import sys
from dataclasses import MISSING, fields

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ROOT, "src"))

from chemsim.reactions.template import ReactionTemplate  # noqa: E402

PSV = os.path.join(_ROOT, "data", "templates", "templates.psv")

# The same table in two files, and the split is about who writes them rather
# than about what a row means. ``templates.psv`` is hand-typed, one mechanism
# somebody argued for; ``literal.psv`` is regenerated by
# ``tools/extract_templates.py`` from the catalog steps themselves, so rule 5
# applies to it and not to the first. Every row of both goes through the same
# columns, the same validation and the same constructor.
LITERAL_PSV = os.path.join(_ROOT, "data", "templates", "literal.psv")
TABLES = (PSV, LITERAL_PSV)
OUT = os.path.join(_ROOT, "src", "chemsim", "reactions", "template_data.py")

TIERS = ("family", "literal")

# ---------------------------------------------------------------------------
# WHERE A ``ReactionTemplate`` MAY BE CONSTRUCTED, AND NOWHERE ELSE
# ---------------------------------------------------------------------------
# ``qualified name -> why it is allowed``. Three of the four build a row of this
# table; the fourth rebuilds a template that arrived inside a save file. Anything
# else is a template that is not a row, which is the thing T1 exists to stop, so
# this is asserted as a SET and a new entry has to be argued for here.
CONSTRUCTION_SITES = {
    "reactions/template_data.py:TemplateRecord.build":
        "the loader: one row -> the template it describes",
    "reactions/library.py:_row":
        "a row with the caller's overrides",
    "reactions/library.py:_catalysed_row":
        "a row whose homogeneous catalyst the caller chooses",
    "reactions/library.py:_surface_row":
        "a row whose solid catalyst the caller chooses",
    "engine/scenario.py:TemplateSpec.build":
        "a template that arrived inside a save file, not from this table",
}

PACKAGE = os.path.join(_ROOT, "src", "chemsim")


def construction_sites() -> dict[str, int]:
    """Every ``ReactionTemplate(...)`` under ``src/chemsim`` -> how many.

    Keyed ``path:qualname``, so two sites in one function count together and a
    site moved between functions reads as one gone and one arrived.
    """
    found: dict[str, int] = {}
    for dirpath, _dirs, files in os.walk(PACKAGE):
        for fname in sorted(files):
            if not fname.endswith(".py"):
                continue
            path = os.path.join(dirpath, fname)
            rel = os.path.relpath(path, PACKAGE).replace(os.sep, "/")
            with open(path, encoding="utf-8") as fh:
                tree = ast.parse(fh.read(), path)
            stack: list[str] = []

            def walk(node: ast.AST) -> None:
                named = isinstance(
                    node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
                if named:
                    stack.append(node.name)
                for child in ast.iter_child_nodes(node):
                    if (isinstance(child, ast.Call)
                            and isinstance(child.func, ast.Name)
                            and child.func.id == "ReactionTemplate"):
                        key = f"{rel}:{'.'.join(stack)}" if stack else rel
                        found[key] = found.get(key, 0) + 1
                    walk(child)
                if named:
                    stack.pop()

            walk(tree)
    return found


def check_construction_sites() -> None:
    """The set of construction sites is exactly ``CONSTRUCTION_SITES``."""
    found = construction_sites()
    extra = sorted(set(found) - set(CONSTRUCTION_SITES))
    gone = sorted(set(CONSTRUCTION_SITES) - set(found))
    if extra or gone:
        lines = [f"{PACKAGE}: the ReactionTemplate construction sites moved."]
        for k in extra:
            lines.append(f"  NEW  {k} ({found[k]} site(s))")
        lines.append(
            "       A template constructed outside the loader is a template "
            "that is not a row, which is what T1 removed. Add the row instead, "
            "or argue the new site into CONSTRUCTION_SITES.")
        for k in gone:
            lines.append(f"  GONE {k} -- {CONSTRUCTION_SITES[k]}")
        raise SystemExit("\n".join(lines))


# ---------------------------------------------------------------------------
# the fields, read off the dataclass so a new one cannot be dropped
# ---------------------------------------------------------------------------


def template_fields() -> dict[str, object]:
    """``ReactionTemplate``'s own fields -> their defaults.

    ``_rxn`` is the compiled RDKit reaction, derived in ``__post_init__`` from
    the SMARTS, so it is not data and is not a column.
    """
    out: dict[str, object] = {}
    for f in fields(ReactionTemplate):
        if f.name.startswith("_"):
            continue
        out[f.name] = None if f.default is MISSING else f.default
    return out


FIELD_DEFAULTS = template_fields()

# The curation columns -- what a row says that a ``ReactionTemplate`` does not.
CURATION_COLUMNS = ("tier", "class", "source", "notes")

# Column order in the file. ``Ea`` is spelled ``Ea_J`` so the unit is in the
# header, and the SMARTS sits second from last because it runs to 200 characters
# and would otherwise bury every numeric column.
COLUMNS = (
    "name", "tier", "class", "phase", "reversible", "A", "Ea_J", "alpha",
    "orders", "solid_catalyst", "electrons", "hammett_rho", "hammett_slot",
    "hammett_saturation", "smarts", "source", "notes",
)
_COLUMN_FIELD = {"Ea_J": "Ea"}


def check_columns() -> None:
    """Every ``ReactionTemplate`` field has a column, and no column is spare."""
    covered = {_COLUMN_FIELD.get(c, c) for c in COLUMNS} - set(CURATION_COLUMNS)
    missing = set(FIELD_DEFAULTS) - covered
    spare = covered - set(FIELD_DEFAULTS)
    if missing or spare:
        raise SystemExit(
            f"{PSV}: the column set and ReactionTemplate's fields disagree.\n"
            f"  fields with no column: {sorted(missing)}\n"
            f"  columns with no field: {sorted(spare)}\n"
            "A template field that does not round-trip is a field the game does "
            "not have -- see this script's docstring and TemplateSpec's."
        )


# ---------------------------------------------------------------------------
# reading the table
# ---------------------------------------------------------------------------


def _num(cell: str, where: str) -> float:
    try:
        return float(cell)
    except ValueError:
        raise SystemExit(f"{where}: {cell!r} is not a number") from None


def read_table(paths: tuple[str, ...] = TABLES) -> list[dict]:
    """The template tables -> rows, validated structurally and nothing more.

    An empty optional cell means the ``ReactionTemplate`` default, taken off the
    dataclass, so a default lives in exactly one place. A name that appears in
    both files is the same collision as a name appearing twice in one: the name
    is what every report and every ``Snapshot`` calls the reaction.
    """
    rows: list[dict] = []
    seen: set[str] = set()
    for path in paths:
        rows.extend(_read_one(path, seen))
    if not rows:
        raise SystemExit(f"{paths}: no rows")
    return rows


def _read_one(path: str, seen: set[str]) -> list[dict]:
    rows: list[dict] = []
    if path is LITERAL_PSV and not os.path.exists(path):
        # The generated half may legitimately not be there yet; the hand-typed
        # half may not be missing, and open() says so.
        return rows
    with open(path, encoding="utf-8") as fh:
        for n, raw in enumerate(fh, 1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            cells = [c.strip() for c in line.split("|")]
            where = f"{path}:{n}"
            if len(cells) != len(COLUMNS):
                raise SystemExit(
                    f"{where}: expected {len(COLUMNS)} fields "
                    f"({' | '.join(COLUMNS)}), got {len(cells)}"
                )
            cell = dict(zip(COLUMNS, cells))
            name = cell["name"]
            if not name:
                raise SystemExit(f"{where}: a template needs a name")
            if name in seen:
                raise SystemExit(
                    f"{where}: {name!r} appears twice. A template's name is what "
                    f"every report and every Snapshot calls the reaction, so it "
                    f"is the key here."
                )
            seen.add(name)
            if cell["tier"] not in TIERS:
                raise SystemExit(
                    f"{where}: tier {cell['tier']!r} is not one of {TIERS}. The "
                    f"tier is what keeps a literal row out of the default "
                    f"library -- see T2a in BACKLOG.md."
                )
            if cell["reversible"] not in ("yes", "no"):
                raise SystemExit(
                    f"{where}: reversible is {cell['reversible']!r}, not "
                    f"'yes' or 'no'"
                )
            row = {
                "tier": cell["tier"],
                "catalog_classes": tuple(
                    c.strip() for c in cell["class"].split("+") if c.strip()),
                "source": cell["source"],
                "notes": cell["notes"],
                "name": name,
                "smarts": cell["smarts"],
                "A": _num(cell["A"], f"{where} A"),
                "Ea": _num(cell["Ea_J"], f"{where} Ea_J"),
                "reversible": cell["reversible"] == "yes",
                "phase": cell["phase"],
                "alpha": (FIELD_DEFAULTS["alpha"] if not cell["alpha"]
                          else _num(cell["alpha"], f"{where} alpha")),
                "orders": (None if not cell["orders"] else tuple(
                    _num(o, f"{where} orders") for o in cell["orders"].split(","))),
                "solid_catalyst": cell["solid_catalyst"] or None,
                "electrons": (FIELD_DEFAULTS["electrons"] if not cell["electrons"]
                              else int(cell["electrons"])),
                "hammett_rho": (
                    FIELD_DEFAULTS["hammett_rho"] if not cell["hammett_rho"]
                    else _num(cell["hammett_rho"], f"{where} hammett_rho")),
                "hammett_slot": (
                    FIELD_DEFAULTS["hammett_slot"] if not cell["hammett_slot"]
                    else int(cell["hammett_slot"])),
                "hammett_saturation": (
                    FIELD_DEFAULTS["hammett_saturation"]
                    if not cell["hammett_saturation"]
                    else _num(cell["hammett_saturation"],
                              f"{where} hammett_saturation")),
            }
            if not cell["source"]:
                raise SystemExit(
                    f"{where}: {name!r} has an empty source. A barrier without "
                    f"its provenance is a number nobody can check."
                )
            rows.append(row)
    return rows


def build(row: dict) -> ReactionTemplate:
    """One row -> the template it describes. Validation is the constructor's."""
    return ReactionTemplate(**{f: row[f] for f in FIELD_DEFAULTS})


# ---------------------------------------------------------------------------
# the generated module
# ---------------------------------------------------------------------------

HEADER = '''"""Layer 2 -- the reaction templates, as data. GENERATED, do not edit.

    python tools/build_templates.py

Source: ``data/templates/templates.psv``. Adding a template is adding a row to
that file and running the line above; the row carries every field
``ReactionTemplate`` has, plus the tier, the catalog classes it covers, the
barrier\'s provenance and a note.

A ``tier="literal"`` row is extracted from ONE catalog step with kinetics from
a class policy table, and it may not enter the default library implicitly. S11
established that selectivity is a rate ratio between templates racing in the
same flask, so a hundred rows carrying policy-table kinetics would make every
multi-template flask\'s selectivity noise. ``load_templates()`` defaults to the
family tier and says which tier it loaded.
"""

from __future__ import annotations

from dataclasses import dataclass

from chemsim.reactions.template import ReactionTemplate

# Every field of ``ReactionTemplate`` that is data. Generated from the dataclass
# itself, so a field added there breaks the build until the table gains a column
# -- which is the assertion P4 wanted: about the SET of fields, not about
# whichever field somebody remembered.
TEMPLATE_FIELDS = (
'''

BODY = '''

@dataclass(frozen=True)
class TemplateRecord:
    """One row of ``templates.psv``, as data. ``build()`` makes the template."""

    name: str
    tier: str
    catalog_classes: tuple[str, ...]
    source: str
    notes: str
    smarts: str
    A: float
    Ea: float
    reversible: bool
    phase: str
    alpha: float
    orders: tuple[float, ...] | None
    solid_catalyst: str | None
    electrons: int
    hammett_rho: float
    hammett_slot: int
    hammett_saturation: float

    def build(self) -> ReactionTemplate:
        return ReactionTemplate(**{f: getattr(self, f) for f in TEMPLATE_FIELDS})
'''

FOOTER = '''

def load_templates(
    tier: str = "family",
    classes: tuple[str, ...] | None = None,
) -> list[ReactionTemplate]:
    """The templates of one tier, optionally narrowed to some catalog classes.

    ``tier`` defaults to ``"family"`` and that default is load-bearing: it is
    what keeps an extracted literal row out of a flask that did not ask for one.
    Pass ``tier="any"`` to load every row, which is a deliberate act.

    ``classes`` narrows to rows carrying at least one of the named
    ``route_steps.psv`` reaction classes.
    """
    out = []
    for rec in TEMPLATES.values():
        if tier != "any" and rec.tier != tier:
            continue
        if classes is not None and not set(rec.catalog_classes) & set(classes):
            continue
        out.append(rec.build())
    return out


def template_classes(tier: str = "any") -> dict[str, tuple[str, ...]]:
    """catalog reaction class -> the template names covering it.

    Several templates may cover one class: that is a class covered by a FAMILY,
    and the credit belongs to the family rather than to a member.
    """
    out: dict[str, list[str]] = {}
    for rec in TEMPLATES.values():
        if tier != "any" and rec.tier != tier:
            continue
        for cls in rec.catalog_classes:
            out.setdefault(cls, []).append(rec.name)
    return {c: tuple(n) for c, n in sorted(out.items())}


def tier_counts() -> dict[str, int]:
    """How many rows per tier -- COUNTED, so a report cannot assert it."""
    out: dict[str, int] = {}
    for rec in TEMPLATES.values():
        out[rec.tier] = out.get(rec.tier, 0) + 1
    return dict(sorted(out.items()))
'''


def render(rows: list[dict]) -> str:
    out = [HEADER]
    for f in FIELD_DEFAULTS:
        out.append(f"    {f!r},")
    out.append(")")
    out.append(BODY)
    out.append("")
    out.append("TEMPLATES: dict[str, TemplateRecord] = {")
    for row in rows:
        out.append(f"    {row['name']!r}: TemplateRecord(")
        out.append(f"        name={row['name']!r},")
        out.append(f"        tier={row['tier']!r},")
        out.append(f"        catalog_classes={row['catalog_classes']!r},")
        out.append(f"        source={row['source']!r},")
        out.append(f"        notes={row['notes']!r},")
        out.append(f"        smarts={row['smarts']!r},")
        out.append(f"        A={row['A']!r}, Ea={row['Ea']!r},")
        out.append(f"        reversible={row['reversible']!r}, "
                   f"phase={row['phase']!r},")
        out.append(f"        alpha={row['alpha']!r}, orders={row['orders']!r},")
        out.append(f"        solid_catalyst={row['solid_catalyst']!r}, "
                   f"electrons={row['electrons']!r},")
        out.append(f"        hammett_rho={row['hammett_rho']!r}, "
                   f"hammett_slot={row['hammett_slot']!r},")
        out.append(f"        hammett_saturation={row['hammett_saturation']!r},")
        out.append("    ),")
    out.append("}")
    out.append(FOOTER)
    return "\n".join(out)


# ---------------------------------------------------------------------------


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify only; a stale module or a drifted row fails")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    check_columns()
    check_construction_sites()
    rows = read_table()
    for row in rows:
        build(row)                       # the constructor's own validation

    print(" and ".join(os.path.relpath(p, _ROOT) for p in TABLES))
    print(f"  {len(rows)} rows, tiers "
          f"{ {t: sum(1 for r in rows if r['tier'] == t) for t in TIERS} }")
    print(f"  {len({c for r in rows for c in r['catalog_classes']})} catalog "
          f"classes covered")
    print(f"  every row builds; {len(CONSTRUCTION_SITES)} construction sites in "
          f"src/chemsim, all of them loaders")

    text = render(rows)
    if args.dry_run:
        print(f"\n--dry-run: nothing written "
              f"({len(text)} bytes would go to {OUT})")
        return 0
    if args.check:
        try:
            with open(OUT, encoding="utf-8") as fh:
                have = fh.read()
        except FileNotFoundError:
            print(f"\n{OUT} does not exist; run without --check")
            return 1
        if have != text:
            print(f"\n{OUT} is stale. Run: python tools/build_templates.py")
            return 1
        print(f"  {OUT} is current")
        return 0
    # CRLF, matching every other generated module in this repo. A generator
    # that flips a file's line endings makes its own output undiffable.
    with open(OUT, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write(text)
    print(f"\nwrote {OUT}  ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
